import { BookOpen, Check, ChevronDown, Download, FileText, Highlighter, Paperclip, Plus, Search, Stamp, Upload, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { candidates } from "../data/boards";

export function PaperlessStudioDashboard(){return <div className="ps-dashboard"><header><b>HUNTER / STUDIO</b><nav><button>今日材料</button><button>候选人</button><button>岗位</button><button>Agent</button></nav><span>于一凡</span></header><main><section className="ps-note"><small>WORKING PAPER / 08.06</small><h1>具身智能人才交付</h1><p>先确认岗位角色层级，再审核 12 位寻访候选人。</p><em>今日工作纸</em></section><section className="ps-stack"><article><span>01 / RESUME</span><h2>林昊 · 候选人材料</h2><p>VLA、真机部署、24 人团队管理。</p><button>打开批注</button></article><article><span>02 / POSITION</span><h2>具身智能算法负责人</h2><p>岗位画像已更新，等待客户确认。</p></article><article><span>03 / RESEARCH</span><h2>团队背景研究</h2><p>6 个来源已经核验。</p></article></section><aside><header><h2>材料索引</h2><b>07</b></header>{candidates.map((c,i)=><button key={c.name}><span>0{i+1}</span><b>{c.name}</b><em>{c.score}</em></button>)}</aside></main></div>}

export function PaperlessStudioComponents(){const root=useRef(null);const [open,setOpen]=useState(null);const [type,setType]=useState("候选人材料");const [tags,setTags]=useState(["VLA","真实部署"]);const [checks,setChecks]=useState([true,true,false]);const [radio,setRadio]=useState(0);const [toggle,setToggle]=useState(true);const [score,setScore]=useState(76);const [tab,setTab]=useState(0);const [upload,setUpload]=useState(false);const [modal,setModal]=useState(false);const [drawer,setDrawer]=useState(false);const [toast,setToast]=useState(false);const [motion,setMotion]=useState(0);const [tag,setTag]=useState("");useEffect(()=>{const f=e=>{if(!root.current?.contains(e.target))setOpen(null)};document.addEventListener("pointerdown",f);return()=>document.removeEventListener("pointerdown",f)},[]);const add=()=>{if(tag.trim()&&!tags.includes(tag.trim()))setTags([...tags,tag.trim()]);setTag("")};return <div className="ps-components" ref={root}><header className="ps-cover"><small>COMPONENT WORKBOOK / 07</small><h1>无纸化材料组件</h1><p>每组组件都像一份可阅读、可批注、可归档的工作材料。</p><i>HUNTER STUDIO</i></header>
 <nav className="ps-binder">{["操作","表单","选择","数据","反馈","动效"].map((x,i)=><button className={tab===i?"active":""} onClick={()=>setTab(i)} key={x}>{x}</button>)}</nav>
 <section className="ps-paper actions"><aside>01</aside><main><header><h2>操作命令</h2><span>WORKING COPY</span></header><div><button className="primary"><Plus/>新建材料</button><button><Highlighter/>添加批注</button><button><Download/>导出</button><button className="danger">删除</button><button disabled>不可用</button><span><button>提交审核</button><button onClick={()=>setOpen(open==="submit"?null:"submit")}><ChevronDown/></button>{open==="submit"&&<menu><button onClick={()=>{setToast(true);setOpen(null)}}>提交当前版本</button><button onClick={()=>setOpen(null)}>保存为草稿</button></menu>}</span></div></main></section>
 <section className="ps-paper form"><aside>02</aside><main><header><h2>材料表单</h2><span>EDITABLE</span></header><div className="ps-fields"><label><span>检索材料</span><div><Search/><input defaultValue="具身智能 算法负责人"/></div></label><label className="error"><span>联系邮箱</span><input defaultValue="linhao@"/><small>请输入完整邮箱地址</small></label><label className="popup"><span>材料类型</span><button onClick={()=>setOpen(open==="type"?null:"type")}>{type}<ChevronDown/></button>{open==="type"&&<menu>{["候选人材料","岗位说明","客户研究","论文证据"].map(x=><button onClick={()=>{setType(x);setOpen(null)}} key={x}>{type===x&&<Check/>}{x}</button>)}</menu>}</label><label className="popup"><span>审阅日期</span><button onClick={()=>setOpen(open==="date"?null:"date")}>2026 年 8 月 6 日</button>{open==="date"&&<div className="ps-date"><b>AUGUST</b><div>{Array.from({length:14},(_,i)=><button onClick={()=>setOpen(null)} key={i}>{i+1}</button>)}</div></div>}</label><label className="wide"><span>材料正文</span><textarea defaultValue="候选人具备 VLA、真机部署及跨团队交付经验，建议进入首轮沟通。"/></label><label className="wide"><span>索引标签</span><div className="ps-tags">{tags.map(x=><em key={x}>{x}<button onClick={()=>setTags(tags.filter(y=>y!==x))}><X/></button></em>)}<input value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();add()}}}/><button onClick={add}>添加</button></div></label><label className="wide"><span>原始附件</span><button className="ps-upload" onClick={()=>setUpload(!upload)}><Paperclip/><div><b>{upload?"林昊简历.pdf · 解析中":"上传 PDF 或 DOCX"}</b><small>{upload?"68% · 点击取消":"保留原始文件"}</small></div></button></label></div></main></section>
 <section className="ps-paper choices"><aside>03</aside><main><header><h2>审阅选项</h2></header><div><article>{["仅看有批注","包含历史版本","隐藏已归档"].map((x,i)=><button onClick={()=>setChecks(checks.map((v,n)=>n===i?!v:v))} key={x}><i className={checks[i]?"on":""}>{checks[i]&&<Check/>}</i>{x}</button>)}</article><article>{["最新材料","重要程度","来源数量"].map((x,i)=><button onClick={()=>setRadio(i)} key={x}><i className={radio===i?"on":""}/>{x}</button>)}</article><article><button onClick={()=>setToggle(!toggle)}>通过门禁后自动归档<i className={toggle?"on":""}><em/></i></button><label>证据阈值 <b>{score}</b><input type="range" value={score} onChange={e=>setScore(e.target.value)}/></label></article></div></main></section>
 <section className="ps-paper data"><aside>04</aside><main><header><h2>材料目录</h2><span>4 RECORDS</span></header>{candidates.map((c,i)=><article key={c.name}><span>0{i+1}</span><FileText/><div><b>{c.name} · 推荐材料</b><p>{c.role} · {c.company}</p></div><em>{c.score}</em><button>打开</button></article>)}<footer><button onClick={()=>setModal(true)}>归档 Modal</button><button onClick={()=>setDrawer(true)}>批注 Drawer</button><button onClick={()=>setToast(true)}>显示状态</button></footer></main></section>
 <section className={`ps-motion motion-${motion}`}><header><span>05</span><h2>纸面专属动效</h2>{["纸张滑入","翻页比较","批注钉入","归档盖章"].map((x,i)=><button className={motion===i+1?"active":""} onClick={()=>setMotion(i+1)} key={x}>{x}</button>)}</header><div><article><small>CANDIDATE NOTE</small><h3>林昊 · 推荐材料</h3><p>角色层级与项目经验匹配。</p></article><aside>批注：确认到岗周期</aside><strong><Stamp/>ARCHIVED</strong></div></section>
 {modal&&<div className="ps-overlay"><div className="ps-modal"><small>ARCHIVE MATERIAL</small><h2>归档当前材料？</h2><p>归档后仍可在历史版本中查看。</p><footer><button onClick={()=>setModal(false)}>取消</button><button onClick={()=>{setModal(false);setToast(true)}}>确认归档</button></footer></div></div>}{drawer&&<aside className="ps-drawer"><button onClick={()=>setDrawer(false)}><X/></button><small>MARGIN NOTE / 03</small><h2>审阅批注</h2><blockquote>建议先确认候选人的到岗周期，再生成客户推荐材料。</blockquote><button>定位原文</button></aside>}{toast&&<div className="ps-toast"><Stamp/><span><b>材料已归档</b><small>版本 03 已保留</small></span><button onClick={()=>setToast(false)}><X/></button></div>}</div>}
