import {
  ArrowDown, Bot, BriefcaseBusiness, Building2, CalendarDays, Check, ChevronDown,
  ChevronLeft, ChevronRight, CircleAlert, Download, Filter, LayoutDashboard, LoaderCircle,
  LockKeyhole, MoreHorizontal, Plus, Search, SlidersHorizontal, Trash2, Upload, UserRound, UsersRound, X,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { candidates, jobs } from "../data/boards";

export function QuietOperationsDashboard() {
  return <div className="qo-dashboard">
    <aside><b>H</b>{[[LayoutDashboard,"工作台"],[UserRound,"候选人"],[BriefcaseBusiness,"岗位"],[Building2,"公司"],[Bot,"Agent"]].map(([Icon,label],i)=><button className={i===0?"active":""} key={label}><Icon/><span>{label}</span></button>)}</aside>
    <main><header><div><small>2026 / 08 / 06</small><h1>静默运营台</h1></div><label><Search/><input placeholder="搜索候选人、岗位或公司"/></label><button><Plus/>新建任务</button></header>
      <section className="qo-metrics">{[["待确认","18","+6"],["流程中","32","+4"],["今日联系","11","+18%"],["Agent 运行","3","1 需处理"]].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></article>)}</section>
      <div className="qo-grid"><section className="qo-table"><header><h2>候选人运营台账</h2><button><Filter/>筛选</button></header><div className="qo-row head"><span>候选人</span><span>公司</span><span>匹配</span><span>流程</span><span>更新</span></div>{candidates.map(c=><div className="qo-row" key={c.name}><span><i>{c.initials}</i><b>{c.name}<small>{c.role}</small></b></span><span>{c.company}</span><strong>{c.score}</strong><em>{c.stage}</em><time>今天 10:32</time></div>)}</section>
        <section className="qo-queue"><header><h2>今天优先处理</h2><b>04</b></header>{["确认林昊到岗周期","审核 12 位寻访结果","准备客户周报","处理平台登录"].map((x,i)=><button key={x}><i>{String(i+1).padStart(2,"0")}</i><span>{x}<small>{i<2?"今天完成":"本周完成"}</small></span><ChevronRight/></button>)}</section>
        <section className="qo-jobs"><header><h2>岗位进展</h2></header>{jobs.map(j=><article key={j.title}><div><b>{j.title}</b><small>{j.company} · {j.active} 位</small></div><strong>{j.progress}%</strong><i><em style={{width:`${j.progress}%`}}/></i></article>)}</section></div>
    </main>
  </div>;
}

export function QuietOperationsComponents() {
  const root=useRef(null);const [menu,setMenu]=useState(null);const [status,setStatus]=useState("推进中");const [cities,setCities]=useState(["北京","上海"]);const [tags,setTags]=useState(["VLA","真机部署"]);const [checks,setChecks]=useState([true,false,true]);const [radio,setRadio]=useState(0);const [toggle,setToggle]=useState(true);const [score,setScore]=useState(72);const [tab,setTab]=useState(0);const [selected,setSelected]=useState([]);const [upload,setUpload]=useState(false);const [modal,setModal]=useState(false);const [drawer,setDrawer]=useState(false);const [toast,setToast]=useState(false);const [motion,setMotion]=useState(0);const [tagText,setTagText]=useState("");
  useEffect(()=>{const close=e=>{if(!root.current?.contains(e.target))setMenu(null)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[]);
  const addTag=()=>{const value=tagText.trim();if(value&&!tags.includes(value))setTags([...tags,value]);setTagText("")};
  return <div className="qo-components" ref={root}>
    <header className="qo-component-head"><div><span>01 / COMPONENT SYSTEM</span><h1>运营台账组件</h1><p>更粗的边界、稳定尺寸和紧凑层级，适合高频重复操作。</p></div><dl><div><dt>控件高度</dt><dd>40 px</dd></div><div><dt>边界</dt><dd>1.5 px</dd></div><div><dt>信息密度</dt><dd>高</dd></div></dl></header>
    <section className="qo-action-matrix"><h2>操作与导航</h2><nav>{["工作台","候选人","岗位","公司","Agent"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</nav><div><button className="primary"><Plus/>主要操作</button><button><Filter/>筛选</button><button><Download/>下载</button><button className="danger"><Trash2/>删除</button><button disabled><LockKeyhole/>不可用</button><span className="qo-split"><button>开始寻访</button><button onClick={()=>setMenu(menu==="split"?null:"split")}><ChevronDown/></button>{menu==="split"&&<menu><button onClick={()=>{setToast(true);setMenu(null)}}>立即开始</button><button onClick={()=>setMenu(null)}>定时运行</button></menu>}</span></div></section>
    <section className="qo-form-ledger"><h2>表单与选择</h2><div className="qo-fields"><label><span>搜索</span><div><Search/><input defaultValue="具身智能 算法负责人"/></div><small>空格、中文或英文逗号均可分隔</small></label><label className="error"><span>联系邮箱</span><div><input defaultValue="linhao@"/><CircleAlert/></div><small>请输入完整邮箱地址</small></label>
      <label className="popup"><span>单选下拉</span><button onClick={()=>setMenu(menu==="single"?null:"single")}>{status}<ChevronDown/></button>{menu==="single"&&<menu>{["全部状态","人才储备","推进中","已入职","失败"].map(x=><button className={x===status?"selected":""} onClick={()=>{setStatus(x);setMenu(null)}} key={x}>{x===status&&<Check/>}{x}</button>)}</menu>}</label>
      <label className="popup wide"><span>可搜索多选</span><button onClick={()=>setMenu(menu==="cities"?null:"cities")}><span>{cities.map(x=><em key={x}>{x}</em>)}</span><ChevronDown/></button>{menu==="cities"&&<menu className="multi"><input placeholder="搜索或按回车添加" onKeyDown={e=>{if(e.key==="Enter"&&e.currentTarget.value.trim()){setCities([...new Set([...cities,e.currentTarget.value.trim()])]);e.currentTarget.value=""}}}/>{["北京","上海","深圳","杭州"].map(x=><button onClick={()=>setCities(cities.includes(x)?cities.filter(y=>y!==x):[...cities,x])} key={x}><i className={cities.includes(x)?"checked":""}>{cities.includes(x)&&<Check/>}</i>{x}</button>)}<footer><button onClick={()=>setCities([])}>清空</button><button onClick={()=>setMenu(null)}>完成</button></footer></menu>}</label>
      <label className="popup"><span>时间范围</span><button onClick={()=>setMenu(menu==="date"?null:"date")}><CalendarDays/>07-01 至 08-06<ChevronDown/></button>{menu==="date"&&<div className="qo-calendar"><header><button><ChevronLeft/></button><b>2026 年 8 月</b><button><ChevronRight/></button></header><div>{Array.from({length:31},(_,i)=><button className={i>0&&i<7?"range":""} key={i}>{i+1}</button>)}</div><footer><button onClick={()=>setMenu(null)}>取消</button><button onClick={()=>setMenu(null)}>应用</button></footer></div>}</label>
      <label className="wide"><span>岗位说明</span><textarea defaultValue="负责具身智能算法方向，推动 VLA 模型进入真机部署。"/></label>
      <label className="wide"><span>标签编辑</span><div className="qo-tags">{tags.map(x=><em key={x}>{x}<button onClick={()=>setTags(tags.filter(y=>y!==x))}><X/></button></em>)}<input value={tagText} onChange={e=>setTagText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addTag()}}}/><button onClick={addTag}><Plus/></button></div></label>
      <label className="wide"><span>文件上传</span><button className="qo-upload" onClick={()=>setUpload(!upload)}>{upload?<><LoaderCircle className="spin"/><b>正在解析 林昊简历.pdf</b><i><em/></i><X/></>:<><Upload/><b>上传简历</b><small>PDF、DOCX · 最大 20 MB</small></>}</button></label></div>
      <div className="qo-choices"><div><b>复选框</b>{["仅看已确认","包括人才储备","隐藏已入库"].map((x,i)=><button onClick={()=>setChecks(checks.map((v,n)=>n===i?!v:v))} key={x}><i className={checks[i]?"checked":""}>{checks[i]&&<Check/>}</i>{x}</button>)}</div><div><b>单选</b>{["按匹配度","按更新时间","按流程阶段"].map((x,i)=><button onClick={()=>setRadio(i)} key={x}><i className={radio===i?"checked":""}/>{x}</button>)}</div><div><b>开关与滑杆</b><button onClick={()=>setToggle(!toggle)}>自动确认低风险结果<i className={toggle?"on":""}><em/></i></button><label>最低匹配分 <strong>{score}</strong><input type="range" value={score} onChange={e=>setScore(e.target.value)}/></label></div></div>
    </section>
    <section className="qo-data"><header><h2>数据、状态与分页</h2><nav>{["全部 64","待确认 18","推进中 32","已入库 14"].map((x,i)=><button className={tab===i?"active":""} onClick={()=>setTab(i)} key={x}>{x}</button>)}</nav></header><div className="qo-filter"><label><Search/><input placeholder="搜索候选人"/></label><button><Building2/>公司<ChevronDown/></button><button><SlidersHorizontal/>更多筛选</button>{selected.length>0&&<strong>已选 {selected.length} 人 <button onClick={()=>setToast(true)}>批量加入流程</button></strong>}</div><div className="qo-data-row head"><span/><span>候选人</span><span>公司</span><span>匹配</span><span>流程</span></div>{candidates.map(c=><div className="qo-data-row" key={c.name}><button onClick={()=>setSelected(selected.includes(c.name)?selected.filter(x=>x!==c.name):[...selected,c.name])}><i className={selected.includes(c.name)?"checked":""}>{selected.includes(c.name)&&<Check/>}</i></button><span><b>{c.name}</b><small>{c.role}</small></span><span>{c.company}</span><strong>{c.score}</strong><em>{c.stage}</em></div>)}<footer><span>共 64 条</span><button disabled><ChevronLeft/></button><button className="active">1</button><button>2</button><button><ChevronRight/></button></footer></section>
    <section className="qo-assets"><h2>业务资产与反馈</h2><div><article><span>候选人</span><h3>林昊</h3><p>具身智能算法负责人 · 穹境机器人</p><strong>94</strong><footer><button onClick={()=>setDrawer(true)}>查看详情</button><button className="primary">加入流程</button></footer></article><article><span>岗位</span><h3>具身智能算法负责人</h3><p>18 位候选人 · 推进率 72%</p><i><em/></i><footer><button>岗位详情</button><button className="primary">开始寻访</button></footer></article><article><span>Agent</span><h3>公司调研 · 运行中</h3><p>正在核验证据，已运行 08:42</p><footer><button>暂停</button><button className="primary">查看运行</button></footer></article></div><nav><button onClick={()=>setModal(true)}>打开 Modal</button><button onClick={()=>setDrawer(true)}>打开 Drawer</button><button onClick={()=>setToast(true)}>显示 Toast</button></nav></section>
    <section className={`qo-motion m-${motion}`}><header><h2>台账专属动效</h2>{["行更新","批量收拢","状态盖章","数据刷新"].map((x,i)=><button className={motion===i+1?"active":""} onClick={()=>setMotion(i+1)} key={x}>{x}</button>)}</header><div><article><span>LIN HAO / 094</span><b>候选人记录已更新</b><em>技术复试</em></article><article><span>BATCH / 012</span><b>12 位候选人等待确认</b><em>已收拢</em></article><strong>已写入台账</strong></div></section>
    {modal&&<div className="qo-overlay"><div role="dialog" className="qo-modal"><h2>将候选人加入岗位流程？</h2><p>林昊将进入“技术复试”，现有资料不会被修改。</p><footer><button onClick={()=>setModal(false)}>取消</button><button className="primary" onClick={()=>{setModal(false);setToast(true)}}>确认加入</button></footer></div></div>}
    {drawer&&<aside className="qo-drawer"><header><h2>林昊</h2><button onClick={()=>setDrawer(false)}><X/></button></header><b>具身智能算法负责人</b><p>穹境机器人 · 北京 · 12 年经验</p><dl><dt>匹配度</dt><dd>94</dd><dt>当前流程</dt><dd>技术复试</dd></dl></aside>}
    {toast&&<div className="qo-toast"><Check/><b>操作已完成</b><button onClick={()=>setToast(false)}><X/></button></div>}
  </div>;
}
