import {
  Activity, AlertTriangle, Aperture, ArrowRight, BadgeCheck, Binary, Bot, Check, ChevronDown,
  CircleGauge, CircleUserRound, Command, Crosshair, FileCheck2, Fingerprint, Gauge, GitBranch,
  Layers3, Link2, LockKeyhole, Mail, Network, Plus, Radio, ScanLine, Search, ShieldCheck,
  SlidersHorizontal, Sparkles, Target, Upload, UserRoundCheck, X, Zap,
} from "lucide-react";
import { useState } from "react";

const LabHeading=({board,code,children})=><header className="tech-lab-heading"><div><span>{code} / COMPONENT LANGUAGE</span><h1>{board.name}</h1></div><p>{children}</p></header>;

function NeuralComponents({board}){const [channel,setChannel]=useState(1);const [locked,setLocked]=useState(false);return <section className="concept-components cc-neural"><LabHeading board={board} code="SIGNAL">组件以状态灯、通道、刻度和波形反馈呈现人才校准。</LabHeading><div className="instrument-console"><div className="instrument-commands"><span>COMMAND KEYS</span><button className="signal-primary" onClick={()=>setLocked(!locked)}><i/><Target/>{locked?"信号已锁定":"锁定人才信号"}</button><button><i/><Crosshair/>重新校准</button><button disabled><i/>权限受限</button><button className="signal-danger"><i/><AlertTriangle/>排除噪声</button></div><div className="channel-bank"><header><Activity/><span>CHANNEL BANK</span><b>0{channel+1}</b></header>{["角色层级","技术能力","行业轨迹","稳定性"].map((x,i)=><button key={x} className={channel===i?"active":""} onClick={()=>setChannel(i)}><i/><span>{x}</span><b>{[92,88,73,81][i]}</b></button>)}</div><label className="signal-input"><span>人才搜索信号</span><div><Search/><input defaultValue="具身智能  VLA  算法负责人"/><b>0.87</b></div><small>按回车发送一次校准脉冲</small></label><div className="scope-component"><svg viewBox="0 0 700 130" preserveAspectRatio="none"><path d="M0 70 C50 68 60 20 105 70 S190 120 235 68 S330 19 380 70 S475 118 520 65 S620 22 700 70"/></svg><span/></div><div className="instrument-states"><article><i className="live"/><b>正常</b><small>通道稳定</small></article><article><i className="scan"/><b>加载</b><small>扫描证据</small></article><article><i className="fault"/><b>错误</b><small>信号失真</small></article><article><LockKeyhole/><b>权限</b><small>仅管理员</small></article></div></div></section>}

function EvidenceComponents({board}){const [cite,setCite]=useState(2);const [diff,setDiff]=useState(false);return <section className="concept-components cc-evidence"><LabHeading board={board} code="PROOF">组件通过引用编号、来源脊线和校样差异建立证据链。</LabHeading><div className="proof-workbench"><aside><span>REFERENCE INDEX</span>{["简历原文","个人主页","OpenAlex","公司官网"].map((x,i)=><button key={x} onClick={()=>setCite(i)} className={cite===i?"active":""}><b>[{i+1}]</b>{x}<i/></button>)}</aside><main><div className="proof-actions"><button className="proof-primary"><FileCheck2/>加入结论 <sup>[{cite+1}]</sup></button><button><Link2/>查看来源</button><button className="proof-redline" onClick={()=>setDiff(true)}>比较修改</button><button disabled>不可用</button></div><label className="source-spine"><span>SOURCE / 0{cite+1}</span><input defaultValue={["候选人原始简历","https://linhao.ai/about","OpenAlex Author A502…","穹境机器人团队"][cite]}/><BadgeCheck/></label><blockquote><sup>[{cite+1}]</sup>负责具身智能算法团队，推动 VLA 模型从研究原型进入真机部署。<footer>来源已核验 · 可信度 0.92</footer></blockquote><div className="proof-rows"><article><span>[A]</span><div><b>管理经验</b><small>建议从“未填写”更新为“30 人团队”</small></div><button><Check/>采纳</button></article><article className="proof-error"><span>[B]</span><div><b>任职时间冲突</b><small>两个来源的开始时间相差 3 个月</small></div><button>查看冲突</button></article><article className="proof-empty"><span>∅</span><div><b>没有更多证据</b><small>可继续联网探索</small></div></article></div></main>{diff&&<div className="proof-diff"><header><span>校样差异 / ROLE</span><button onClick={()=>setDiff(false)}><X/></button></header><div><del>算法专家</del><ins>算法负责人</ins></div><footer><button onClick={()=>setDiff(false)}>取消</button><button>确认替换</button></footer></div>}</div></section>}

function RadarComponents({board}){const [depth,setDepth]=useState(2);const [path,setPath]=useState(false);return <section className="concept-components cc-radar"><LabHeading board={board} code="RADAR">组件围绕扫描范围、关系节点和触达路径构造。</LabHeading><div className="radar-kit"><div className="radial-control"><span>SCAN DEPTH</span><div>{[1,2,3,4].map(i=><button key={i} onClick={()=>setDepth(i)} className={depth===i?"active":""}>{i}<small>跳</small></button>)}</div><i className={`depth-${depth}`}/></div><div className="radar-actions"><button className="launch"><ScanLine/>发射探测</button><button><Radio/>持续监听</button><button disabled><LockKeyhole/>受限扇区</button></div><label className="radar-search"><Crosshair/><input placeholder="输入公司、人物或研究方向"/><b>↵</b></label><div className="node-specimens"><button><i className="person"/><span><b>林昊</b><small>目标候选人 · 1 跳</small></span><em>92</em></button><button><i className="company"/><span><b>穹境机器人</b><small>目标公司 · 已核验</small></span><em>86</em></button><button className="node-loading"><i/><span><b>扫描关系节点</b><small>正在读取公开路径…</small></span></button><button className="node-error"><AlertTriangle/><span><b>关系链断开</b><small>来源已失效</small></span><em>重试</em></button></div><button className="path-trigger" onClick={()=>setPath(true)}><Network/>查看最短触达路径 <ArrowRight/></button>{path&&<div className="path-sheet"><header><span>PATH / 03 HOPS</span><button onClick={()=>setPath(false)}><X/></button></header>{["你","王蕾","林昊"].map((x,i)=><div key={x}><i>{i+1}</i><b>{x}</b>{i<2&&<em/>}</div>)}<button>使用此路径</button></div>}</div></section>}

function FocusComponents({board}){const [level,setLevel]=useState(1);return <section className="concept-components cc-focus"><LabHeading board={board} code="APERTURE">组件通过光圈、视野层级和渐进字段控制认知负担。</LabHeading><div className={`focus-kit level-${level}`}><div className="aperture-control"><span>INFORMATION APERTURE</span><div className="aperture-disc"><i/><i/><i/><b>{["精简","标准","完整"][level]}</b></div><nav>{[0,1,2].map(i=><button key={i} onClick={()=>setLevel(i)} className={level===i?"active":""}>{["低","中","高"][i]}</button>)}</nav></div><main><div className="focus-buttons"><button>稍后处理</button><button className="focus-confirm"><Check/>进入沟通</button><button className="focus-reject">不合适</button></div><label className="focus-field"><span>当前判断</span><textarea defaultValue="候选人的角色层级和量产经验与岗位一致，建议进入首次沟通。"/></label><div className="progressive-fields"><label><span>角色结论</span><input defaultValue="高度适配"/></label><label><span>主要风险</span><input defaultValue="到岗周期待确认"/></label><label><span>次要证据</span><input defaultValue="论文 6 篇，专利 11 项"/></label></div><div className="focus-states"><span className="clear"><i/>判断清晰</span><span className="thinking"><i/>正在聚焦</span><span className="blurred"><i/>信息不足</span><span className="locked"><LockKeyhole/>不可编辑</span></div></main></div></section>}

function MissionComponents({board}){const [incident,setIncident]=useState(false);return <section className="concept-components cc-mission"><LabHeading board={board} code="CONTROL">组件使用命令键、事件包和 Incident 面板处理自动化任务。</LabHeading><div className="command-kit"><div className="command-keys"><button className="cmd-run"><Zap/><span>RUN</span><b>启动任务</b></button><button><Command/><span>PAUSE</span><b>暂停队列</b></button><button className="cmd-alert" onClick={()=>setIncident(true)}><AlertTriangle/><span>TAKEOVER</span><b>人工接管</b></button><button disabled><LockKeyhole/><span>LOCKED</span><b>强制写入</b></button></div><div className="event-packets"><header><span>EVENT PACKETS / LIVE</span><b>04</b></header><article className="success"><time>14:32:08</time><i/><div><b>证据核验完成</b><small>已通过全部写入门禁</small></div><em>OK</em></article><article className="running"><time>14:31:42</time><i/><div><b>读取候选人详情</b><small>PAGE 03 / CARD 08</small></div><em>LIVE</em></article><article className="warning"><time>14:29:12</time><i/><div><b>平台登录即将失效</b><small>建议在 10 分钟内处理</small></div><em>WARN</em></article></div><label className="command-slot"><span>自然语言命令</span><div><Command/><input placeholder="例如：仅重新处理失败的脉脉任务"/><kbd>⌘ ↵</kbd></div></label><div className="mission-state-matrix">{[["正常","12","green"],["等待","04","amber"],["失败","02","red"],["权限","—","lock"]].map(([n,v,c])=><article key={n} className={c}><span>{n}</span><b>{v}</b><i/></article>)}</div>{incident&&<div className="incident-modal"><header><AlertTriangle/><span>接管平台异常</span></header><p>脉脉登录已失效。任务结果和 checkpoint 已保留。</p><footer><button onClick={()=>setIncident(false)}>暂不处理</button><button>打开平台</button></footer></div>}</div></section>}

function HumanComponents({board}){const [trust,setTrust]=useState(72);return <section className="concept-components cc-human"><LabHeading board={board} code="BIOSIGNAL">组件围绕人物身份、沟通节律和信任反馈设计。</LabHeading><div className="human-kit"><div className="identity-cells"><button className="active"><span>林</span><div><b>林昊</b><small>直接关系 · 可信</small></div><i className="pulse"/></button><button><span>周</span><div><b>周雨澄</b><small>二跳关系 · 待核验</small></div><i/></button><button className="identity-empty"><Plus/><span>添加联系人</span></button></div><div className="contact-recorder"><button className="record"><i/><Radio/>记录联系</button><label><span>沟通主题</span><input defaultValue="具身智能算法负责人"/></label><button><Mail/>生成联系建议</button></div><div className="trust-calibrator"><header><Fingerprint/><span>信任校准</span><b>{trust}%</b></header><div className="trust-dial"><i style={{"--trust":`${trust*3.6}deg`}}/><span>{trust}</span></div><input type="range" min="0" max="100" value={trust} onChange={e=>setTrust(e.target.value)}/><small>来自 3 位共同联系人和 7 次互动</small></div><div className="rhythm-timeline"><span>CONTACT RHYTHM</span>{["首次添加关系","查看岗位资料","共同联系人确认","等待首次沟通"].map((x,i)=><article key={x}><i className={i===3?"waiting":""}/><time>{["07/12","07/20","08/01","NOW"][i]}</time><b>{x}</b></article>)}</div><div className="human-states"><span><i/>可联系</span><span><i/>等待回复</span><span><i/>关系较弱</span><span><LockKeyhole/>隐私受限</span></div></div></section>}

function CircuitComponents({board}){const [gates,setGates]=useState([1,1,0]);const toggle=i=>setGates(x=>x.map((v,n)=>n===i?1-v:v));return <section className="concept-components cc-circuit"><LabHeading board={board} code="LOGIC">组件用端子、逻辑门和电路状态表示筛选与评分规则。</LabHeading><div className="circuit-kit"><div className="gate-bank"><span>LOGIC GATES</span>{["硬门禁","有条件匹配","评分权重"].map((x,i)=><button key={x} onClick={()=>toggle(i)} className={gates[i]?"on":""}><i>{gates[i]?"1":"0"}</i><b>{x}</b><em>{i===0?"AND":i===1?"IF":"WEIGHT"}</em></button>)}</div><div className="terminal-fields"><label><span>INPUT A / 目标职级</span><div><i/><input defaultValue="总监、负责人"/><b>AND</b></div></label><label><span>INPUT B / 最低经验</span><div><i/><input defaultValue="8"/><b>YEAR</b></div></label><label className="terminal-error"><span>INPUT C / 行业范围</span><div><i/><input defaultValue="机器人，具身智能"/><AlertTriangle/></div><small>“机器人”范围较宽，建议增加方向条件。</small></label></div><div className="circuit-status"><article className="pass"><Binary/><b>PASS</b><span>林昊 · 94</span></article><article className="condition"><GitBranch/><b>CONDITION</b><span>周雨澄 · -12%</span></article><article className="block"><LockKeyhole/><b>BLOCK</b><span>宋北辰 · 层级不足</span></article><article className="loading"><i/><b>CALCULATE</b><span>正在运行规则电路</span></article></div><button className="circuit-apply"><Zap/>应用并运行电路</button></div></section>}

function SpectrumComponents({board}){const [weights,setWeights]=useState([80,65,92]);return <section className="concept-components cc-spectrum"><LabHeading board={board} code="SPECTRUM">组件通过波段、棱镜和双样本槽比较人才能力。</LabHeading><div className="spectrum-kit"><div className="prism-actions"><button className="prism-primary"><Aperture/>分解人才光谱</button><button><GitBranch/>叠合样本</button><button className="spectral-danger">移除波段</button><button disabled>样本锁定</button></div><div className="spectral-faders">{["模型能力","机器人系统","团队管理"].map((x,i)=><label key={x}><span>{x}<b>{weights[i]}</b></span><input type="range" value={weights[i]} onChange={e=>setWeights(w=>w.map((v,n)=>n===i?e.target.value:v))}/><i style={{width:`${weights[i]}%`}}/></label>)}</div><div className="sample-slots"><article><span>SAMPLE A</span><i>林</i><b>林昊</b><small>光谱重合 94%</small></article><div className="versus">VS</div><article><span>SAMPLE B</span><i>周</i><b>周雨澄</b><small>光谱重合 88%</small></article></div><div className="spectrum-chips"><span className="wave-a">VLA / 96</span><span className="wave-b">真机部署 / 88</span><span className="wave-c">团队管理 / 82</span><span className="wave-gap">证据缺口</span></div><div className="spectral-states"><article><i/><b>稳定谱线</b></article><article><i/><b>正在扫描</b></article><article><i/><b>波段缺失</b></article><article><LockKeyhole/><b>锁定样本</b></article></div></div></section>}

function BlueprintComponents({board}){const [layer,setLayer]=useState(0);return <section className="concept-components cc-blueprint"><LabHeading board={board} code="BLUEPRINT">组件以尺寸线、图层、端口和工程批注表达搜索配置。</LabHeading><div className="blueprint-kit"><aside><span>LAYERS</span>{["关键词","公司","城市","详情规则"].map((x,i)=><button key={x} onClick={()=>setLayer(i)} className={layer===i?"active":""}><i>{layer===i&&<Check/>}</i><b>{x}</b><em>0{i+1}</em></button>)}</aside><main><div className="blueprint-tools"><button className="stamp-primary">执行图纸</button><button><Layers3/>复制图层</button><button>R08</button><button disabled><LockKeyhole/></button></div><div className="dimension-fields"><label><span>X / 关键词组</span><div><input defaultValue="具身智能 + VLA"/><i/></div><small>AND RELATION</small></label><label><span>Y / 期望城市</span><div><input defaultValue="北京，上海"/><i/></div><small>2 VALUES</small></label></div><div className="connector-sample"><div><span>KEYWORD</span><b>具身智能 + VLA</b><i/></div><svg viewBox="0 0 600 100"><path d="M150 50 H280 V24 H420"/><path d="M280 50 V78 H420"/></svg><div><span>COMPANY</span><b>目标公司 6</b><i/></div><div><span>CITY</span><b>北京 · 上海</b><i/></div></div><blockquote><b>ANNOTATION / 0{layer+1}</b><p>每组关键词独立执行，组内满足全部条件。</p></blockquote><div className="blueprint-states"><span>✓ 图纸有效</span><span>… 正在装配</span><span>! 端口断开</span><span>⌁ 只读图层</span></div></main></div></section>}

function CopilotComponents({board}){const [dock,setDock]=useState("people");const [suggestion,setSuggestion]=useState(true);return <section className="concept-components cc-copilot"><LabHeading board={board} code="COPILOT">组件像智能座舱：固定命令、磁吸模块和上下文副驾协同工作。</LabHeading><div className="copilot-kit"><nav className="hardware-dock">{[["job","岗位"],["people","人才"],["map","Mapping"],["agent","Agent"]].map(([id,x],i)=><button key={id} onClick={()=>setDock(id)} className={dock===id?"active":""}><i>{i+1}</i><span>{x}</span></button>)}</nav><main><div className="deck-controls"><div className="toggle-paddles"><button className="active">匹配</button><button>寻访</button><button>研究</button></div><button className="deck-primary"><Command/>打开命令中心</button><button><SlidersHorizontal/>重排模块</button></div><div className="magnetic-modules"><article className="module-wide"><header><span>ACTIVE MODULE</span><b>LIVE</b></header><div className="deck-row"><i>林</i><div><b>林昊</b><small>算法负责人 · 94 分</small></div><Gauge/></div><div className="deck-row loading"><i/><div><b>读取下一位候选人</b><small>证据核验中…</small></div></div></article><article><header><span>CONTEXT</span></header><p>岗位目标为负责人，重点判断团队管理与量产交付。</p><span className="deck-chip">角色一致</span><span className="deck-chip">证据完整</span></article><article className="permission-module"><LockKeyhole/><b>预算设置</b><small>仅工作区所有者可修改</small></article></div>{suggestion&&<div className="copilot-suggestion"><Sparkles/><div><b>副驾建议</b><span>优先确认候选人的到岗周期。</span></div><button onClick={()=>setSuggestion(false)}><X/></button></div>}</main></div></section>}

export const componentLabsA={"precision-desk":NeuralComponents,"editorial-intelligence":EvidenceComponents,"talent-constellation":RadarComponents,"calm-focus":FocusComponents,"command-center":MissionComponents,"human-studio":HumanComponents,"bauhaus-workflow":CircuitComponents,"data-atelier":SpectrumComponents,"kinetic-blueprint":BlueprintComponents,"adaptive-modules":CopilotComponents};
