import {
  Anchor, AlertTriangle, ArrowRight, BadgeCheck, Bot, Check, ChevronRight, CircleGauge,
  ClipboardCheck, Clock3, Code2, Compass, Database, Eye, FileArchive, FileCheck2,
  Fingerprint, GitCompareArrows, Hash, KeyRound, Layers3, LibraryBig, ListFilter, Map,
  Navigation, Network, PackageCheck, Pause, Play, Plus, Radio, ScanSearch, Search,
  ShieldCheck, Sparkles, Stamp, Tags, TimerReset, UserRoundCheck, UsersRound, X,
} from "lucide-react";
import { useMemo, useState } from "react";

const LabHeading=({board,code,children})=><header className="tech-lab-heading"><div><span>{code} / COMPONENT LANGUAGE</span><h1>{board.name}</h1></div><p>{children}</p></header>;

function TapeComponents({board}){const [stack,setStack]=useState(2);return <section className="concept-components cc-tape"><LabHeading board={board} code="TAPE">组件通过翻牌、穿孔票据和决策栈支持高频筛选。</LabHeading><div className="tape-kit"><div className="split-flap"><span>TOP SIGNAL</span><div>{String(94+stack).padStart(3,"0").split("").map((n,i)=><i key={i}>{n}</i>)}</div><button onClick={()=>setStack(x=>(x+1)%5)}>刷新信号</button></div><div className="ticket-controls"><button className="ticket-accept"><Check/>进入沟通</button><button>放入人才池</button><button className="ticket-reject">不合适</button><button disabled>已锁定</button></div><label className="ticker-filter"><ListFilter/><input defaultValue="具身智能  VLA  总监"/><b>LIVE</b></label><div className="component-tickets">{[["林昊","94","LOCKED"],["周雨澄","88","NEW"],["陈松","83","REVIEW"]].map((x,i)=><article key={x[0]}><i/><span>0{i+1}</span><div><b>{x[0]}</b><small>ROLE {+x[1]-4} · SKILL {x[1]}</small></div><strong>{x[1]}</strong><em>{x[2]}</em></article>)}</div><div className="decision-stack"><span>DECISION STACK</span><button onClick={()=>setStack(stack+1)}><Plus/>加入一张票</button><i style={{"--stack":Math.min(stack,5)}}/><b>{String(stack).padStart(2,"0")}</b></div><div className="tape-states"><span>↑ 新信号</span><span>↻ 处理中</span><span>! 票据异常</span><span>⌧ 权限锁定</span></div></div></section>}

function TelemetryComponents({board}){const [playing,setPlaying]=useState(true);return <section className="concept-components cc-telemetry"><LabHeading board={board} code="TELEMETRY">组件使用时间码、通道、事件包和解码器呈现寻访过程。</LabHeading><div className="telemetry-kit"><div className="playback-controls"><button onClick={()=>setPlaying(!playing)} className="telemetry-play">{playing?<Pause/>:<Play/>}<span>{playing?"暂停":"回放"}</span><b>14:32:08</b></button><button><Radio/>标记事件</button><button><Clock3/>跳到最新</button><button disabled><LockKey/>删除遥测</button></div><div className="channel-switches">{["API","CARD","DETAIL","PDF","VISION"].map((x,i)=><button className={i<4?"active":""} key={x}><i/><span>{x}</span><b>CH{i+1}</b></button>)}</div><div className="waveform-input"><label>TIME RANGE / 18:00</label><div>{[1,2,3].map(i=><svg key={i} viewBox="0 0 700 50" preserveAspectRatio="none"><path d={i===2?"M0 26 C50 25 60 6 110 25 S200 44 250 24 S340 7 400 25 S520 44 580 23 S650 13 700 25":"M0 25 L70 25 L85 8 L100 42 L120 14 L140 25 L260 25 L280 5 L300 45 L325 25 L500 25 L530 9 L550 40 L575 25 L700 25"}/></svg>)}</div><input type="range" defaultValue="68"/></div><div className="packet-components"><article className="packet-ok"><time>14:32:08</time><i/><div><b>详情读取完成</b><small>PACKET / 001048</small></div><em>OK</em></article><article className="packet-load"><time>14:31:52</time><i/><div><b>PDF 视觉解析</b><small>PAGE 02 / 03</small></div><em>DECODE</em></article><article className="packet-fail"><time>14:29:17</time><AlertTriangle/><div><b>通道响应超时</b><small>保留 checkpoint 后重试</small></div><button>重试</button></article><article className="packet-empty"><span>NO SIGNAL</span><b>当前时间段没有事件包</b></article></div></div></section>}

function ProtocolComponents({board}){const [signed,setSigned]=useState(false);return <section className="concept-components cc-protocol"><LabHeading board={board} code="PROTOCOL">组件使用签名、哈希链和双段确认保护业务写入。</LabHeading><div className="protocol-kit"><div className="signature-actions"><button className="sign-primary" onClick={()=>setSigned(true)} disabled={signed}><KeyRound/>{signed?"签名完成":"签名并写入"}</button><button><FileCheck2/>查看证据</button><button className="sign-danger">撤销写入</button><button disabled><LockKey/>系统门禁</button></div><label className="hash-field"><Hash/><span>CONTENT HASH</span><input readOnly value="8FA3-29D1-C740-77AE"/><BadgeCheck/></label><div className="protocol-steps">{[["资料锁定","LOCK"],["证据门禁","PASS"],["用户签名",signed?"SIGNED":"WAIT"],["业务写入",signed?"COMMIT":"HOLD"]].map((x,i)=><article key={x[0]} className={signed||i<2?"done":i===2?"current":""}><i>{signed||i<2?<Check/>:<Fingerprint/>}</i><b>{x[0]}</b><span>{x[1]}</span></article>)}</div><div className="signed-row"><span>职位</span><del>算法专家</del><ArrowRight/><ins>算法负责人</ins><code>47E0-D2</code></div><div className="protocol-alert"><ShieldCheck/><div><b>系统安全检查始终生效</b><span>即使启用自动确认，不合格数据仍不能写入。</span></div></div><div className="protocol-states"><span><BadgeCheck/>已验证</span><span><i/>校验中</span><span><AlertTriangle/>签名冲突</span><span><LockKey/>权限不足</span></div></div></section>}

function AtlasComponents({board}){const [layer,setLayer]=useState(0);return <section className="concept-components cc-atlas"><LabHeading board={board} code="ATLAS">组件以地图图层、注释针和语义范围控制研究阅读。</LabHeading><div className="atlas-kit"><aside><span>MAP LAYERS</span>{["公司集群","岗位迁移","研究方向","人才密度"].map((x,i)=><button key={x} onClick={()=>setLayer(i)} className={layer===i?"active":""}><i>{layer===i&&<Check/>}</i>{x}<b>0{i+1}</b></button>)}</aside><main><div className="atlas-tools"><button className="atlas-primary"><Map/>应用图层</button><button><Layers3/>叠加比较</button><button><Search/>坐标搜索</button><button disabled>只读章节</button></div><label className="coordinate-search"><span>SEMANTIC COORDINATE</span><div><Search/><input defaultValue="具身智能 / VLA / 北京"/><b>↵</b></div></label><div className="map-legend-components"><button><i className="hot"/>高度相关 <b>27</b></button><button><i className="move"/>能力可迁移 <b>14</b></button><button><i className="verify"/>待核验 <b>09</b></button></div><div className="annotation-pins"><article><i>01</i><div><b>北京人才密度中心</b><small>智元、银河通用、星尘智能</small></div><button><Eye/>定位</button></article><article className="annotation-loading"><i/><div><b>计算语义邻域</b><small>正在读取 193 条来源…</small></div></article><article className="annotation-error"><AlertTriangle/><div><b>图层数据不完整</b><small>GitHub 来源未配置</small></div><button>查看降级</button></article></div></main></div></section>}

function NavigatorComponents({board}){const [anchor,setAnchor]=useState(false);return <section className="concept-components cc-navigator"><LabHeading board={board} code="NAVIGATOR">组件使用航点、信标和恢复锚点管理长时间搜索。</LabHeading><div className="navigator-kit"><div className="nav-controls"><button className="beacon-primary"><Radio/>发射信标</button><button onClick={()=>setAnchor(true)}><Anchor/>保存锚点</button><button><Compass/>校准航向</button><button disabled>越界区域</button></div><label className="beacon-input"><Navigation/><span>目标信标</span><input defaultValue="上海人工智能实验室 / 具身智能"/><b>N31°</b></label><div className="waypoint-components">{["需求确认","机构解析","多源召回","证据核验","结果交付"].map((x,i)=><button key={x} className={i<2?"done":i===2?"active":""}><i>{i<2?<Check/>:<Radio/>}</i><b>{x}</b><small>{i<2?"已通过":i===2?"航行中":"等待"}</small></button>)}</div><div className="nav-log-component"><header><span>VOYAGE LOG</span><b>18:32:41</b></header><article><i/><time>14:32</time><span>发现 17 位相关论文作者</span></article><article><i/><time>14:28</time><span>机构 ID 与子机构已联合</span></article><article className="nav-empty"><span>下一航段暂无事件</span></article></div>{anchor&&<div className="anchor-toast"><Anchor/><div><b>恢复锚点已保存</b><span>ANCHOR / 07 · 14:32</span></div><button onClick={()=>setAnchor(false)}><X/></button></div>}</div></section>}

function WorkshopComponents({board}){const [stamp,setStamp]=useState("run");return <section className="concept-components cc-workshop"><LabHeading board={board} code="WORKSHOP">组件像工位、卡匣和质量章，强调输入、返工与交付。</LabHeading><div className="workshop-kit"><div className="workshop-keys"><button className="key-primary" onClick={()=>setStamp("run")}><Code2/><b>RUN</b><span>开始编译</span></button><button onClick={()=>setStamp("rework")}><TimerReset/><b>REWORK</b><span>退回返工</span></button><button onClick={()=>setStamp("pass")}><Stamp/><b>PASS</b><span>通过门禁</span></button><button disabled><LockKey/><b>LOCK</b><span>强制交付</span></button></div><div className="material-slots-component"><label><span>INPUT MATERIAL / A</span><div><FileArchive/><input defaultValue="理想汽车"/></div></label><label><span>INPUT MATERIAL / B</span><div><Plus/><input placeholder="补充调研范围"/></div></label><button><Plus/>添加材料槽</button></div><div className="cartridge-list">{["理解公司范围","规划信息来源","生成字段草稿","执行自检"].map((x,i)=><article key={x} className={i<2?"done":i===2?"active":""}><i>{i<2?<Check/>:i+1}</i><b>{x}</b><span>{i<2?"PASS":i===2?"RUN":"WAIT"}</span></article>)}</div><div className={`quality-stamp stamp-${stamp}`}><Stamp/><b>{stamp==="run"?"RUNNING":stamp==="rework"?"REWORK":"PASSED"}</b><small>QUALITY GATE / {stamp==="pass"?"04":"03"} OF 04</small></div><div className="workshop-states"><span><i/>材料就绪</span><span><i/>编译中</span><span><i/>门禁失败</span><span><LockKey/>交付锁定</span></div></div></section>}

function RailComponents({board}){const [auto,setAuto]=useState(true);return <section className="concept-components cc-rail"><LabHeading board={board} code="RAIL">组件以站点、闸机和旁路表示自动处理与人工确认。</LabHeading><div className="rail-kit"><div className="rail-actions"><button className="rail-go"><Navigation/>发车并执行</button><button><Clock3/>稍后停靠</button><button className="rail-stop">停止线路</button><button disabled>线路锁定</button></div><div className="track-switch"><span>确认方式</span><button onClick={()=>setAuto(false)} className={!auto?"active":""}>人工确认</button><i/><button onClick={()=>setAuto(true)} className={auto?"active":""}>门禁后自动</button></div><div className="station-components">{["输入需求","AI 理解","人工确认","自动执行"].map((x,i)=><article key={x} className={i<2?"passed":i===2?"current":""}><i>{i<2?<Check/>:i+1}</i><div><b>{x}</b><small>{i===2?"任务在本站停靠":"自动区间"}</small></div>{i===2&&<button>确认通过</button>}{i<3&&<em/>}</article>)}</div><label className="ticket-field"><span>TASK TICKET</span><div><Navigation/><input defaultValue="具身智能算法负责人 / 岗位解析"/><b>LINE 07</b></div></label><div className="rail-exception"><AlertTriangle/><div><b>线路偏航</b><span>平台登录失效，任务已进入旁路并保留结果。</span></div><button>恢复线路</button></div><div className="rail-states"><span>● 运行</span><span>◉ 停靠</span><span>⑂ 旁路</span><span>▣ 权限锁定</span></div></div></section>}

function MeshComponents({board}){const [owner,setOwner]=useState("agent");return <section className="concept-components cc-mesh"><LabHeading board={board} code="MESH">组件通过所有权节点、交接插槽和任务包表达多方协作。</LabHeading><div className="mesh-kit"><div className="ownership-switch">{[["human","猎头"],["agent","Agent"],["proof","证据"],["asset","业务资产"]].map(([id,x])=><button key={id} onClick={()=>setOwner(id)} className={owner===id?"active":""}><i>{id==="agent"?<Bot/>:id==="human"?<UserRoundCheck/>:id==="proof"?<FileCheck2/>:<Database/>}</i><span>{x}</span></button>)}</div><div className="handoff-actions"><button className="handoff-primary"><GitCompareArrows/>发起交接</button><button><UsersRound/>指定责任人</button><button>退回上一泳道</button><button disabled>跨工作区</button></div><div className="task-packets">{[["岗位研究","Agent → 证据","4 个来源"],["候选人审核","Agent → 猎头","12 位人选"],["正式写入","猎头 → 业务资产","3 条记录"]].map((x,i)=><article key={x[0]}><i className={`shape-${i}`}>{i===0?<Bot/>:i===1?<UserRoundCheck/>:<Database/>}</i><div><b>{x[0]}</b><small>{x[1]}</small></div><span>{x[2]}</span><ChevronRight/></article>)}</div><div className="handoff-slot"><span>DROP HANDOFF HERE</span><i/><p>将任务包拖入交接插槽</p></div><div className="mesh-states"><span><i/>已接收</span><span><i/>交接中</span><span><i/>责任冲突</span><span><LockKey/>权限边界</span></div></div></section>}

function PatternComponents({board}){const [chips,setChips]=useState(["VLA","负责人"]);const add=e=>{if(e.key==="Enter"&&e.currentTarget.value.trim()){setChips([...chips,e.currentTarget.value.trim()]);e.currentTarget.value=""}};return <section className="concept-components cc-pattern"><LabHeading board={board} code="PATTERN">组件使用查询晶格、模式芯片、样本块和比较托盘。</LabHeading><div className="pattern-kit"><label className="lattice-input"><ScanSearch/><span>QUERY LATTICE</span><div>{chips.map(x=><b key={x}>{x}<button onClick={()=>setChips(chips.filter(v=>v!==x))}><X/></button></b>)}<input placeholder="输入后按回车" onKeyDown={add}/></div></label><div className="pattern-actions"><button className="pattern-primary"><Search/>运行模式检索</button><button><Tags/>保存模式</button><button><GitCompareArrows/>比较样本</button><button disabled>私有样本</button></div><div className="pattern-chips"><span className="role">角色模式 · 技术负责人</span><span className="skill">技术模式 · VLA</span><span className="track">轨迹模式 · 创业公司</span><span className="missing">证据模式 · 缺失</span></div><div className="sample-components">{[["林昊",94],["周雨澄",88],["陈松",83]].map(([n,s],i)=><article key={n}><div><span>{n.slice(0,1)}</span>{[80+i*3,65+i*6,92-i*4].map((h,j)=><i key={j} style={{height:`${h}%`}}/>)}</div><b>{n}</b><small>共同模式 {3-i}</small><button><Plus/>托盘</button></article>)}</div><div className="compare-dock"><span>COMPARE DOCK</span><i>林</i><i>周</i><button>开始比较 <ArrowRight/></button></div><div className="pattern-empty"><Search/><span>空状态：放宽查询晶格可获得更多样本</span></div></div></section>}

function ArchiveComponents({board}){const [drawer,setDrawer]=useState(false);return <section className="concept-components cc-archive"><LabHeading board={board} code="ARCHIVE">组件通过透明索引片、档案抽屉和时间尺组织长期人才资产。</LabHeading><div className="archive-kit"><div className="archive-actions"><button className="archive-primary" onClick={()=>setDrawer(true)}><FileArchive/>打开档案抽屉</button><button><LibraryBig/>加入馆藏</button><button className="archive-seal">封存记录</button><button disabled>永久删除</button></div><label className="archive-index-field"><span>ARCHIVE INDEX</span><div><Search/><input defaultValue="FTA-026-041 / 林昊"/><b>A1</b></div></label><div className="transparent-tabs"><button className="active">人物档案 <b>38</b></button><button>公司档案 <b>17</b></button><button>研究档案 <b>64</b></button></div><div className="archive-card-component"><i className="sheet-one"/><i className="sheet-two"/><article><header><span>KEY TALENT</span><b>2026</b></header><div><i>林</i><section><b>林昊</b><small>具身智能算法负责人</small></section><BadgeCheck/></div><footer><span>证据 19</span><span>岗位 3</span><span>路径 4</span></footer></article></div><div className="time-ruler"><span>2024</span><i/><span>2025</span><i className="active"/><span>2026</span><i/></div><div className="archive-states"><span>已归档</span><span>显影中</span><span>索引损坏</span><span>只读馆藏</span></div>{drawer&&<aside className="archive-drawer"><header><span>ARCHIVE DRAWER / A1</span><button onClick={()=>setDrawer(false)}><X/></button></header>{["林昊","周雨澄","陈松"].map((x,i)=><button key={x}><b>FTA-0{i+41}</b><span>{x}</span><ChevronRight/></button>)}</aside>}</div></section>}

function LockKey(){return <ShieldCheck/>}
export const componentLabsB={"kinetic-ledger":TapeComponents,"physical-telemetry":TelemetryComponents,"institutional-trust":ProtocolComponents,"ai-state-atlas":AtlasComponents,"expedition-search":NavigatorComponents,"compile-workshop":WorkshopComponents,"guided-service":RailComponents,"teamwork-fabric":MeshComponents,"pattern-library":PatternComponents,"digital-curatorial":ArchiveComponents};
