import {
  Anchor, Archive, ArrowRight, BadgeCheck, Bot, Check, ChevronRight, CircleGauge,
  Compass, Database, FileCheck2, GitCompareArrows, Hash, Layers3, LibraryBig,
  Navigation, Network, PackageCheck, Pause, Play, Radio, RotateCcw, ScanSearch,
  Search, ShieldCheck, Sparkles, Stamp, TimerReset, UserRoundCheck, UsersRound, Zap,
} from "lucide-react";
import { useState } from "react";

const MotionHeading=({board,code,children})=><header className="tech-motion-heading"><div><span>{code} / MOTION LANGUAGE</span><h1>{board.name}</h1></div><p>{children}</p></header>;
const Trigger=({onClick,children})=><button className="motion-trigger" onClick={onClick}><Play/> {children}</button>;

function TapeMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-tape"><MotionHeading board={board} code="TICKER">翻牌刷新、票据插入、决策堆叠和撤单分别服务高频筛选。</MotionHeading><div className={`tape-motion-stage run-${run}`}><header><Trigger onClick={()=>setRun(1)}>刷新行情</Trigger><Trigger onClick={()=>setRun(2)}>插入票据</Trigger><Trigger onClick={()=>setRun(3)}>压入决策</Trigger><Trigger onClick={()=>setRun(4)}>撤回一票</Trigger></header><div className="ticker-belt">{["ROLE 94","SKILL 91","INTENT 82","RISK 07","PROOF 88"].map((x,i)=><span key={x}>{x}<i>{i%2?"▲":"●"}</i></span>)}</div><main><article className="motion-ticket mt-a"><i/><b>林昊</b><span>具身智能负责人</span><strong>94</strong></article><article className="motion-ticket mt-b"><i/><b>周雨澄</b><span>VLA 算法专家</span><strong>88</strong></article><article className="motion-ticket mt-new"><i/><b>陈松</b><span>世界模型研究员</span><strong>83</strong></article><div className="motion-decision-stack"><span>DECISION STACK</span><i/><i/><i/><b>03</b></div><div className="voided-ticket">VOID</div></main></div></section>}

function TelemetryMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-telemetry"><MotionHeading board={board} code="REPLAY">时间轴拖动、事件回放、解码和丢包恢复构成可观察反馈。</MotionHeading><div className={`telemetry-motion-stage run-${run}`}><nav><Trigger onClick={()=>setRun(1)}>拖动时间轴</Trigger><Trigger onClick={()=>setRun(2)}>回放事件</Trigger><Trigger onClick={()=>setRun(3)}>解码数据包</Trigger><Trigger onClick={()=>setRun(4)}>恢复丢包</Trigger></nav><main><div className="timecode">14:32:<b>08</b>:19</div><div className="telemetry-waves">{[0,1,2,3].map((x)=><svg key={x} viewBox="0 0 900 70" preserveAspectRatio="none"><path d={x%2?"M0 35 L90 35 L108 8 L125 60 L145 18 L166 35 L360 35 L390 10 L415 61 L440 35 L660 35 L690 14 L715 55 L745 35 L900 35":"M0 38 C60 36 75 12 120 36 S220 61 275 35 S390 11 450 37 S570 60 630 34 S780 12 900 36"}/></svg>)}</div><div className="telemetry-playhead"><i/></div><div className="decode-packet"><Radio/><div><b>PDF 视觉解析</b><span>PACKET / 001048</span></div><em>DECODE</em></div><div className="lost-packet"><Zap/>PACKET LOST</div></main></div></section>}

function ProtocolMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-protocol"><MotionHeading board={board} code="SEAL">结果沿哈希链签名、封存；冲突时整条写入链明确失效。</MotionHeading><div className={`protocol-motion-stage run-${run}`}><header><Trigger onClick={()=>setRun(1)}>计算哈希</Trigger><Trigger onClick={()=>setRun(2)}>完成签名</Trigger><Trigger onClick={()=>setRun(3)}>封存结果</Trigger><Trigger onClick={()=>setRun(4)}>模拟冲突</Trigger></header><main><div className="hash-chain">{["INPUT","PROOF","REVIEW","COMMIT"].map((x,i)=><article key={x}><i>{i<3?<Hash/>:<Database/>}</i><b>{x}</b><code>{["8FA3","29D1","C740","77AE"][i]}</code>{i<3&&<ArrowRight/>}</article>)}</div><div className="signature-orbit"><FingerprintMark/><span>USER SIGNATURE</span></div><div className="protocol-seal"><ShieldCheck/><b>VERIFIED</b><small>HUNTER WRITE PROTOCOL</small></div><div className="hash-conflict"><Zap/><b>HASH CONFLICT</b><span>业务写入已冻结</span></div></main></div></section>}

function AtlasMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-atlas"><MotionHeading board={board} code="LAYER">语义图层通过显隐、聚类、标注和溶解呈现研究范围变化。</MotionHeading><div className={`atlas-motion-stage run-${run}`}><aside><Trigger onClick={()=>setRun(1)}>切换图层</Trigger><Trigger onClick={()=>setRun(2)}>聚合节点</Trigger><Trigger onClick={()=>setRun(3)}>定位注释</Trigger><Trigger onClick={()=>setRun(4)}>溶解弱关系</Trigger></aside><main><div className="atlas-grid"/><div className="atlas-cluster ac-a"><i/><i/><i/><b>公司</b></div><div className="atlas-cluster ac-b"><i/><i/><i/><i/><b>人才</b></div><div className="atlas-cluster ac-c"><i/><i/><b>研究</b></div><svg viewBox="0 0 900 520"><path d="M185 145 C350 90 455 180 665 110"/><path d="M185 145 C360 260 505 300 690 370"/><path d="M665 110 C580 230 590 300 690 370"/></svg><div className="atlas-annotation"><MapPinMark/><b>北京人才密度中心</b><span>27 位可触达候选人</span></div><div className="atlas-layer-label"><Layers3/>LAYER 03 / SEMANTIC</div></main></div></section>}

function NavigatorMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-navigator"><MotionHeading board={board} code="VOYAGE">航点推进、声呐探测、锚点保存和中断恢复对应长任务状态。</MotionHeading><div className={`navigator-motion-stage run-${run}`}><nav><Trigger onClick={()=>setRun(1)}>推进航点</Trigger><Trigger onClick={()=>setRun(2)}>声呐探测</Trigger><Trigger onClick={()=>setRun(3)}>保存锚点</Trigger><Trigger onClick={()=>setRun(4)}>中断恢复</Trigger></nav><main><svg className="voyage-route" viewBox="0 0 1000 420" preserveAspectRatio="none"><path d="M55 330 C180 310 170 120 320 135 S500 340 640 255 S780 70 950 105"/></svg>{["需求","机构","召回","核验","交付"].map((x,i)=><button className={`waypoint wp-${i}`} key={x}><i>{i+1}</i><b>{x}</b></button>)}<span className="voyage-ship"><Navigation/></span><div className="sonar-pulse"><Radio/></div><div className="voyage-anchor"><Anchor/><b>ANCHOR / 03</b></div><div className="recovery-beacon"><RotateCcw/><b>从锚点恢复</b><span>已保留 2,481 条结果</span></div></main></div></section>}

function WorkshopMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-workshop"><MotionHeading board={board} code="ASSEMBLY">材料沿工位流转，失败件退回返工，合格件盖章交付。</MotionHeading><div className={`workshop-motion-stage run-${run}`}><header><Trigger onClick={()=>setRun(1)}>启动传送带</Trigger><Trigger onClick={()=>setRun(2)}>质量盖章</Trigger><Trigger onClick={()=>setRun(3)}>退回返工</Trigger><Trigger onClick={()=>setRun(4)}>完成交付</Trigger></header><main><div className="workshop-belt">{[0,1,2,3,4,5].map(i=><i key={i}/>)}</div><div className="material-crate"><PackageCheck/><b>COMPANY DATA</b></div><div className="workstation ws-a"><Bot/><span>PLAN</span></div><div className="workstation ws-b"><CircleGauge/><span>GATE</span></div><div className="workstation ws-c"><Database/><span>DELIVER</span></div><div className="quality-hammer"><Stamp/></div><div className="rework-chute"><TimerReset/>REWORK</div><div className="delivery-crate"><Check/>PASSED</div></main></div></section>}

function RailMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-rail"><MotionHeading board={board} code="TRANSIT">任务令牌沿自动化轨道运行，在确认站停靠，异常时进入旁路。</MotionHeading><div className={`rail-motion-stage run-${run}`}><header><Trigger onClick={()=>setRun(1)}>自动运行</Trigger><Trigger onClick={()=>setRun(2)}>停靠确认</Trigger><Trigger onClick={()=>setRun(3)}>进入旁路</Trigger><Trigger onClick={()=>setRun(4)}>恢复主线</Trigger></header><main><div className="rail-main-line"/><div className="rail-bypass-line"/>{["输入","理解","确认","执行","写入"].map((x,i)=><article className={`rail-station rs-${i}`} key={x}><i>{i+1}</i><b>{x}</b></article>)}<span className="rail-token"><Navigation/></span><div className="rail-gate"><Pause/><b>WAITING</b></div><div className="rail-bypass"><Zap/>BYPASS</div></main></div></section>}

function MeshMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-mesh"><MotionHeading board={board} code="HANDOFF">任务包跨泳道交接，责任随任务移动，冲突会阻断目标插槽。</MotionHeading><div className={`mesh-motion-stage run-${run}`}><nav><Trigger onClick={()=>setRun(1)}>Agent 交接</Trigger><Trigger onClick={()=>setRun(2)}>人工接管</Trigger><Trigger onClick={()=>setRun(3)}>写入资产</Trigger><Trigger onClick={()=>setRun(4)}>模拟冲突</Trigger></nav><main>{[["AGENT",<Bot/>],["HUMAN",<UserRoundCheck/>],["PROOF",<FileCheck2/>],["ASSET",<Database/>]].map(([x,icon],i)=><section key={x}><header>{icon}<b>{x}</b></header><div className={`mesh-slot ms-${i}`}/></section>)}<article className="handoff-packet"><GitCompareArrows/><b>候选人审核</b><span>12 ITEMS</span></article><div className="ownership-line"><UsersRound/>OWNER / HUNTER</div><div className="handoff-conflict"><Zap/>OWNERSHIP CONFLICT</div></main></div></section>}

function PatternMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-pattern"><MotionHeading board={board} code="REFLOW">样本随模式命中重排，在比较托盘中磁吸对齐并显露差异。</MotionHeading><div className={`pattern-motion-stage run-${run}`}><header><Trigger onClick={()=>setRun(1)}>匹配模式</Trigger><Trigger onClick={()=>setRun(2)}>重排样本</Trigger><Trigger onClick={()=>setRun(3)}>进入比较</Trigger><Trigger onClick={()=>setRun(4)}>显示差异</Trigger></header><main><div className="pattern-query"><ScanSearch/><span>VLA × 负责人 × 创业公司</span></div>{[["林昊",94],["周雨澄",88],["陈松",83],["赵星羽",78]].map(([n,s],i)=><article className={`pattern-sample ps-${i}`} key={n}><i>{n[0]}</i><b>{n}</b><span>{s}</span></article>)}<div className="pattern-magnet"><GitCompareArrows/><b>COMPARE</b></div><div className="pattern-diff"><span>共同模式 3</span><em>差异模式 2</em></div></main></div></section>}

function ArchiveMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-archive"><MotionHeading board={board} code="DEVELOP">档案逐层显影、按时间移动、重编号并最终封存。</MotionHeading><div className={`archive-motion-stage run-${run}`}><nav><Trigger onClick={()=>setRun(1)}>逐层显影</Trigger><Trigger onClick={()=>setRun(2)}>移动时间</Trigger><Trigger onClick={()=>setRun(3)}>重建索引</Trigger><Trigger onClick={()=>setRun(4)}>封存档案</Trigger></nav><main><div className="archive-sheets">{["PROOF","PROFILE","RELATION","DECISION"].map((x,i)=><article className={`archive-sheet as-${i}`} key={x}><span>{x}</span><i>{i===1?"林":""}</i><b>{i===1?"林昊":"FTA / 026"}</b><small>{i===1?"具身智能算法负责人":"ARCHIVE LAYER"}</small></article>)}</div><div className="archive-motion-ruler"><span>2024</span><i/><span>2025</span><i/><span>2026</span><i/></div><div className="archive-renumber"><Hash/>FTA-026-041 → FTA-026-042</div><div className="archive-final-seal"><Archive/><b>SEALED</b><small>2026 / HUNTER</small></div></main></div></section>}

function FingerprintMark(){return <BadgeCheck/>}
function MapPinMark(){return <Compass/>}

export const motionLabsB={
  "kinetic-ledger":TapeMotion,"physical-telemetry":TelemetryMotion,
  "institutional-trust":ProtocolMotion,"ai-state-atlas":AtlasMotion,
  "expedition-search":NavigatorMotion,"compile-workshop":WorkshopMotion,
  "guided-service":RailMotion,"teamwork-fabric":MeshMotion,
  "pattern-library":PatternMotion,"digital-curatorial":ArchiveMotion,
};
