import {
  Activity, Aperture, ArrowRight, Binary, Bot, Check, CircleGauge, Command, Crosshair, FileCheck2,
  Fingerprint, Gauge, GitBranch, Layers3, Link2, Network, Play, Radio, ScanLine,
  ShieldCheck, Sparkles, Target, UserRoundCheck, Zap,
} from "lucide-react";
import { useState } from "react";

const MotionHeading=({board,code,children})=><header className="tech-motion-heading"><div><span>{code} / MOTION LANGUAGE</span><h1>{board.name}</h1></div><p>{children}</p></header>;
const Trigger=({onClick,children})=><button className="motion-trigger" onClick={onClick}><Play/> {children}</button>;

function NeuralMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-neural"><MotionHeading board={board} code="SCAN">扫描、相位对齐、信号锁定和失真定位构成完整反馈。</MotionHeading><div className={`neural-motion-stage run-${run}`}><nav>{["扫描候选人","相位对齐","锁定信号","模拟失真"].map((x,i)=><Trigger key={x} onClick={()=>setRun(i+1)}>{x}</Trigger>)}</nav><div className="motion-scope"><div className="scope-lines"/><svg viewBox="0 0 1000 300" preserveAspectRatio="none"><path className="m-wave-a" d="M0 160 C60 155 70 40 125 160 S230 270 290 155 S410 45 470 160 S600 265 655 155 S800 35 1000 160"/><path className="m-wave-b" d="M0 185 C80 180 90 95 155 180 S290 235 360 178 S490 105 560 182 S710 230 790 175 S900 120 1000 180"/></svg><span className="m-scan"/><div className="signal-lock"><Target/><b>LOCKED</b></div><div className="distortion"><Activity/><span>SIGNAL FAULT / CH03</span></div></div><footer><span>01 扫描游标按数据顺序推进</span><span>02 两条信号在匹配成功时对齐</span><span>03 锁定后反馈固定在数据对象</span></footer></div></section>}

function EvidenceMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-evidence"><MotionHeading board={board} code="CITATION">证据从原文抽取、沿引用线归位，再完成校样替换。</MotionHeading><div className={`evidence-motion-stage run-${run}`}><aside><Trigger onClick={()=>setRun(1)}>抽取证据</Trigger><Trigger onClick={()=>setRun(2)}>归位引用</Trigger><Trigger onClick={()=>setRun(3)}>应用校样</Trigger><Trigger onClick={()=>setRun(4)}>断开来源</Trigger></aside><main><article><span>DOCUMENT / PROFILE</span><p>林昊负责 30 人算法团队，推动具身智能模型进入量产。</p><mark>推动具身智能模型进入量产</mark><sup>[02]</sup></article><svg viewBox="0 0 800 280" preserveAspectRatio="none"><path d="M300 180 C430 180 400 80 560 80"/></svg><blockquote><b>[02] 项目证据</b><p>覆盖数据闭环、训练评测与真机部署。</p><small>SOURCE VERIFIED · 0.92</small></blockquote><div className="proof-replace"><del>算法专家</del><ArrowRight/><ins>算法负责人</ins></div><div className="broken-proof"><Link2/>来源连接失效</div></main></div></section>}

function RadarMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-radar"><MotionHeading board={board} code="SWEEP">雷达扫描、关系命中、路径追踪和范围扩张采用不同的径向运动。</MotionHeading><div className={`radar-motion-stage run-${run}`}><div className="radar-motion-controls"><Trigger onClick={()=>setRun(1)}>执行扫描</Trigger><Trigger onClick={()=>setRun(2)}>追踪路径</Trigger><Trigger onClick={()=>setRun(3)}>扩大范围</Trigger><Trigger onClick={()=>setRun(4)}>隐藏弱关系</Trigger></div><main><div className="motion-rings"/><div className="motion-sweep"/><i className="hit h1"/><i className="hit h2"/><i className="hit h3"/><i className="hit h4"/><svg viewBox="0 0 700 520"><path d="M350 260 C270 220 240 130 180 110"/><path d="M350 260 C450 230 500 150 555 125"/><path d="M350 260 C410 350 520 380 585 420"/></svg><span className="radar-origin"><Crosshair/></span></main><aside><Network/><b>3 条可触达路径</b><small>最近关系距离 1 跳</small></aside></div></section>}

function FocusMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-focus"><MotionHeading board={board} code="APERTURE">动效只改变信息视野和决策焦点，不制造无关位移。</MotionHeading><div className={`focus-motion-stage run-${run}`}><nav><Trigger onClick={()=>setRun(1)}>收窄视野</Trigger><Trigger onClick={()=>setRun(2)}>展开证据</Trigger><Trigger onClick={()=>setRun(3)}>切换焦点</Trigger><Trigger onClick={()=>setRun(4)}>定位错误</Trigger></nav><main><div className="focus-lens"><i/><i/><span>林</span></div><article className="focus-info primary"><small>当前判断</small><b>角色层级适配</b><p>负责人 → 负责人</p></article><article className="focus-info secondary"><small>次要证据</small><b>论文与专利</b><p>6 篇 / 11 项</p></article><article className="focus-info error"><small>需要确认</small><b>到岗周期</b><p>字段尚未填写</p></article></main></div></section>}

function MissionMotion({board}){const [events,setEvents]=useState(2);const [alert,setAlert]=useState(false);return <section className="concept-motion cm-mission"><MotionHeading board={board} code="EVENT BUS">事件插入、告警接管、队列收缩和暂停冻结分别对应真实任务动作。</MotionHeading><div className={`mission-motion-stage ${alert?"alerting":""}`}><header><Trigger onClick={()=>setEvents(events+1)}>注入新事件</Trigger><Trigger onClick={()=>setAlert(true)}>触发告警</Trigger><Trigger onClick={()=>setEvents(Math.max(0,events-1))}>处理队列</Trigger><Trigger onClick={()=>setAlert(false)}>解除告警</Trigger></header><main><div className="event-bus-line"/>{Array.from({length:events+2}).map((_,i)=><article key={`${events}-${i}`}><time>14:{32-i}:0{i}</time><i/><div><b>{["候选人核验完成","读取公开资料","匹配评估运行","等待人工确认","写入业务资产"][i%5]}</b><small>EVENT / {1038+i}</small></div><em>{i===1?"LIVE":"OK"}</em></article>)}</main><aside><div className="alarm-wave"><Zap/></div><b>需要接管</b><span>平台登录状态异常</span><button>打开处理</button></aside></div></section>}

function HumanMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-human"><MotionHeading board={board} code="PULSE">人物反馈来自联系脉冲、信任同步、关系靠拢和消息到达。</MotionHeading><div className={`human-motion-stage run-${run}`}><nav><Trigger onClick={()=>setRun(1)}>记录联系</Trigger><Trigger onClick={()=>setRun(2)}>增强信任</Trigger><Trigger onClick={()=>setRun(3)}>建立关系</Trigger><Trigger onClick={()=>setRun(4)}>收到回复</Trigger></nav><main><div className="human-center"><Fingerprint/><b>林昊</b></div><div className="trust-orbit"><i/><i/></div><svg viewBox="0 0 800 350" preserveAspectRatio="none"><path d="M0 180 L100 180 L120 130 L138 230 L160 80 L185 240 L205 180 L360 180 L390 120 L410 230 L435 70 L460 240 L485 180 L800 180"/></svg><button className="relation-person rp-a"><UserRoundCheck/>王蕾</button><button className="relation-person rp-b"><UserRoundCheck/>你</button><div className="message-arrive">已收到回复</div></main></div></section>}

function CircuitMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-circuit"><MotionHeading board={board} code="CURRENT">数据脉冲会通过、减弱、阻断或因规则编辑重新布线。</MotionHeading><div className={`circuit-motion-stage run-${run}`}><header><Trigger onClick={()=>setRun(1)}>信号通过</Trigger><Trigger onClick={()=>setRun(2)}>有条件匹配</Trigger><Trigger onClick={()=>setRun(3)}>硬门禁拒绝</Trigger><Trigger onClick={()=>setRun(4)}>重新布线</Trigger></header><main><svg viewBox="0 0 900 430" preserveAspectRatio="none"><path className="wire w1" d="M40 90 H280 V190 H410"/><path className="wire w2" d="M40 220 H230 V230 H410"/><path className="wire w3" d="M40 350 H300 V270 H410"/><path className="wire out" d="M530 230 H850"/><path className="wire reroute" d="M230 220 V60 H650 V230"/></svg><div className="motion-gate"><Binary/><b>HARD</b></div><span className="current c1"/><span className="current c2"/><span className="current c3"/><div className="gate-block"><ShieldCheck/>BLOCK</div><div className="gate-score">-12%</div></main></div></section>}

function SpectrumMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-spectrum"><MotionHeading board={board} code="REFRACTION">输入样本经过棱镜分解、波段叠合、权重变化和缺口定位。</MotionHeading><div className={`spectrum-motion-stage run-${run}`}><nav><Trigger onClick={()=>setRun(1)}>分解光谱</Trigger><Trigger onClick={()=>setRun(2)}>叠合样本</Trigger><Trigger onClick={()=>setRun(3)}>调整权重</Trigger><Trigger onClick={()=>setRun(4)}>显示缺口</Trigger></nav><main><div className="motion-prism"><Aperture/></div><span className="white-beam"/><div className="spectral-beams">{["#d54c46","#d8ad65","#5cb7ae","#8ebbe0"].map((c,i)=><i key={c} style={{"--c":c,"--i":i}}/>)}</div><div className="spectral-columns">{[82,94,76,88,71].map((x,i)=><i key={i} style={{"--h":`${x}%`}}><em/></i>)}</div><div className="spectrum-gap">MISSING PROOF</div></main></div></section>}

function BlueprintMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-blueprint"><MotionHeading board={board} code="DRAW">路径绘制、图层装配、版本擦除和错误坐标使用工程图动效。</MotionHeading><div className={`blueprint-motion-stage run-${run}`}><header><Trigger onClick={()=>setRun(1)}>绘制路径</Trigger><Trigger onClick={()=>setRun(2)}>装配图层</Trigger><Trigger onClick={()=>setRun(3)}>比较版本</Trigger><Trigger onClick={()=>setRun(4)}>定位断点</Trigger></header><main><div className="motion-blue-grid"/><div className="layer-card l1"><Layers3/>KEYWORD</div><div className="layer-card l2">COMPANY</div><div className="layer-card l3">CITY</div><svg viewBox="0 0 900 430" preserveAspectRatio="none"><path d="M210 100 H430 V210 H670"/><path d="M210 330 H430 V250 H670"/></svg><span className="version-wiper">R07 / R08</span><i className="breakpoint"><Zap/></i></main></div></section>}

function CopilotMotion({board}){const [run,setRun]=useState(0);return <section className="concept-motion cm-copilot"><MotionHeading board={board} code="DOCK">模块磁吸、上下文建议、布局切换和故障脱离组成副驾反馈。</MotionHeading><div className={`copilot-motion-stage run-${run}`}><nav><Trigger onClick={()=>setRun(1)}>磁吸模块</Trigger><Trigger onClick={()=>setRun(2)}>生成建议</Trigger><Trigger onClick={()=>setRun(3)}>切换布局</Trigger><Trigger onClick={()=>setRun(4)}>脱离故障</Trigger></nav><main><article className="dock-module dm-a"><header>候选人</header><b>林昊 · 94</b><span>角色与技术高度适配</span></article><article className="dock-module dm-b"><header>岗位</header><b>算法负责人</b><span>团队搭建 · VLA</span></article><article className="dock-module dm-c"><header>任务栈</header><b>04 RUNNING</b></article><div className="magnet-track"/><div className="copilot-message"><Sparkles/><b>副驾建议</b><span>优先确认到岗周期</span></div><div className="fault-bay">MODULE FAULT</div></main></div></section>}

export const motionLabsA={"precision-desk":NeuralMotion,"editorial-intelligence":EvidenceMotion,"talent-constellation":RadarMotion,"calm-focus":FocusMotion,"command-center":MissionMotion,"human-studio":HumanMotion,"bauhaus-workflow":CircuitMotion,"data-atelier":SpectrumMotion,"kinetic-blueprint":BlueprintMotion,"adaptive-modules":CopilotMotion};
