import {
  Anchor, ArrowRight, BadgeCheck, Bot, Box, Check, ChevronRight, CircleGauge, ClipboardCheck,
  Clock3, Code2, Compass, Database, Eye, FileArchive, FileCheck2, Fingerprint, GitCompareArrows,
  Globe2, Hash, KeyRound, Layers3, LibraryBig, ListFilter, Map, Navigation, Network, PackageCheck,
  Pause, Play, Radio, ScanSearch, Search, ShieldCheck, Sparkles, Stamp, Tags, TimerReset,
  UserRoundCheck, UsersRound, WandSparkles, Waypoints,
} from "lucide-react";
import { useMemo, useState } from "react";
import { candidates, events, workflow } from "../data/boards";

function TalentTape() {
  const [selected,setSelected]=useState([0,1]);
  const toggle=(i)=>setSelected(x=>x.includes(i)?x.filter(v=>v!==i):[...x,i]);
  return <section className="tech-main talent-tape"><header><div><Radio/><strong>TALENT TAPE / LIVE</strong></div><div className="tape-market"><span>具身智能负责人</span><b>+18</b><span>新增信号</span><b>92.4</b><span>平均质量</span></div><button><ListFilter/>信号过滤</button></header><div className="ticker-ribbon"><div>{["林昊 94 ↑","周雨澄 88 ↑","陈松 83 →","宋北辰 79 ↓","VLA 研究 91 ↑","机器人平台 86 ↑"].map(x=><span key={x}>{x}</span>)}</div></div><aside className="tape-board"><span>POSITION TAPE</span><h1>94</h1><p>最高匹配信号</p><dl><div><dt>待决策</dt><dd>18</dd></div><div><dt>已锁定</dt><dd>{selected.length}</dd></div><div><dt>噪声率</dt><dd>6.8%</dd></div></dl><button>批量策略</button></aside><main className="ticket-stack">{candidates.map((item,i)=><button className={`talent-ticket ${selected.includes(i)?"selected":""}`} key={item.name} onClick={()=>toggle(i)}><i className="perforation"/><span className="ticket-index">0{i+1}</span><div className="ticket-person"><b>{item.name}</b><small>{item.company}</small></div><div className="ticket-signal"><span>ROLE {item.score-4}</span><span>SKILL {item.score}</span><span>PROOF {item.score-7}</span></div><strong>{item.score}</strong><em>{selected.includes(i)?<Check/>:"SELECT"}</em></button>)}</main><aside className="tape-actions"><span>DECISION STACK</span><strong>{String(selected.length).padStart(2,"0")}</strong><p>已锁定候选人，等待批量决定。</p><button>放入人才池</button><button className="tape-primary">进入沟通 <ArrowRight/></button><footer>操作可在 10 分钟内撤销</footer></aside></section>;
}

function TelemetryStation() {
  const [playing,setPlaying]=useState(true);
  const [cursor,setCursor]=useState(63);
  return <section className="tech-main telemetry-station"><header><div><CircleGauge/><strong>CANDIDATE TELEMETRY</strong><span>RUN / 24-081</span></div><div><i/>MAIMAI API <b>HEALTHY</b></div><button onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}{playing?"暂停回放":"继续回放"}</button></header><aside className="telemetry-channels"><span>CHANNELS / 05</span>{["搜索请求","候选人卡片","详情事件","PDF 附件","视觉解析"].map((item,i)=><button className={i<4?"active":""} key={item}><i/><span>{item}</span><b>CH{i+1}</b></button>)}<footer><Clock3/>任务时长 <b>18:42</b></footer></aside><main><div className="telemetry-summary"><div><span>当前页</span><b>03 / 10</b></div><div><span>已读详情</span><b>19</b></div><div><span>附件下载</span><b>07</b></div><div><span>待确认</span><b>12</b></div></div><div className="telemetry-wave"><div className="telemetry-grid"/>{[0,1,2,3].map(i=><svg key={i} viewBox="0 0 900 70" preserveAspectRatio="none"><path d={i%2?"M0 35 L80 35 L110 12 L130 58 L150 24 L175 35 L280 35 L310 20 L330 49 L355 18 L380 35 L520 35 L550 9 L570 60 L600 35 L900 35":"M0 40 C80 38 90 10 150 40 S260 65 330 38 S440 12 520 40 S680 65 760 36 S850 20 900 40"}/></svg>)}<span className="telemetry-cursor" style={{left:`${cursor}%`}}><b>14:32:08</b></span></div><input className="telemetry-scrubber" type="range" min="5" max="95" value={cursor} onChange={e=>setCursor(e.target.value)}/><div className="telemetry-packets">{events.slice(0,4).map((e,i)=><article key={e[0]}><time>{e[0]}:{String(i*7).padStart(2,"0")}</time><i/><div><b>{["候选人详情读取完成","PDF 附件写入任务目录","视觉模型开始解析","匹配评估通过"][i]}</b><span>PACKET / {String(1042+i).padStart(6,"0")}</span></div><em>{i===2?"DECODING":"OK"}</em></article>)}</div></main><aside className="telemetry-inspector"><span>PACKET INSPECTOR</span><h2>PDF 附件解析</h2><div className="decode-sheet"><i/><i/><i/><span>07</span></div><dl><div><dt>文件</dt><dd>resume_07.pdf</dd></div><div><dt>页面</dt><dd>3 PAGE</dd></div><div><dt>视觉兜底</dt><dd>REQUIRED</dd></div><div><dt>输出</dt><dd>VALID</dd></div></dl><button><Eye/>查看原始附件</button></aside></section>;
}

function TrustProtocol() {
  const [signed,setSigned]=useState(false);
  return <section className={`tech-main trust-protocol ${signed?"signed":""}`}><header><div><ShieldCheck/><strong>TRUST WRITE PROTOCOL</strong><span>WRITE / CANDIDATE / 0291</span></div><div className="protocol-hash"><Hash/><span>8FA3 · 29D1 · C740</span></div><button onClick={()=>setSigned(true)} disabled={signed}><KeyRound/>{signed?"已签名":"签名并写入"}</button></header><main><div className="protocol-summary"><span>PROPOSED WRITE</span><h1>候选人信息补全</h1><p>3 个字段等待写入，全部具备可验证证据。</p></div><div className="protocol-chain">{[["01","原始资料","LOCKED"],["02","证据门禁","PASSED"],["03","人工审批",signed?"SIGNED":"WAITING"],["04","业务写入",signed?"COMMITTED":"LOCKED"]].map((x,i)=><article key={x[0]} className={signed||i<2?"done":i===2?"current":""}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><i>{signed||i<2?<Check/>:<Fingerprint/>}</i>{i<3&&<em/>}</article>)}</div><div className="protocol-ledger"><header><span>字段</span><span>当前值</span><span>建议值</span><span>证据签名</span></header>{[["公司","穹境科技","穹境机器人","9C21-A7"],["职位","算法专家","算法负责人","47E0-D2"],["技能","VLA","VLA、真机部署","B311-8F"]].map((row,i)=><div key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><strong>{row[2]}</strong><code>{row[3]}</code><i className={signed?"verified":""}><BadgeCheck/></i></div>)}</div></main><aside><span>APPROVAL IDENTITY</span><div className="identity-key"><Fingerprint/><div><b>于一凡</b><small>工作区所有者</small></div><BadgeCheck/></div><dl><div><dt>写入范围</dt><dd>候选人档案</dd></div><div><dt>影响记录</dt><dd>1 条</dd></div><div><dt>可撤销</dt><dd>24 小时</dd></div></dl><div className="protocol-proof"><FileCheck2/><span>证据完整性</span><b>100%</b></div><footer>安全门禁不能被关闭</footer></aside></section>;
}

function SemanticAtlas() {
  const [layer,setLayer]=useState("company");
  return <section className={`tech-main semantic-atlas atlas-${layer}`}><header><div><Map/><strong>SEMANTIC INTELLIGENCE ATLAS</strong></div><nav>{[["company","公司"],["role","岗位"],["topic","方向"]].map(([id,label])=><button key={id} className={layer===id?"active":""} onClick={()=>setLayer(id)}>{label}</button>)}</nav><button><Search/>搜索图册</button></header><aside className="atlas-chapters"><span>CHAPTERS</span>{["具身智能版图","目标公司集群","关键岗位迁移","人才供给密度","风险与窗口"].map((item,i)=><button key={item} className={i===1?"active":""}><b>0{i+1}</b><span>{item}</span></button>)}<footer><LibraryBig/>研究版本 <b>R06</b></footer></aside><main className="atlas-map"><div className="atlas-coordinates"/><svg viewBox="0 0 900 620" preserveAspectRatio="none"><path d="M70 460 C180 400 160 180 310 220 S420 430 520 350 S620 120 820 165"/><path d="M80 190 C200 90 310 160 390 95 S590 80 820 260"/></svg>{[[22,34,"智元"],[47,52,"银河通用"],[64,28,"穹彻智能"],[73,63,"星尘智能"],[34,72,"逐际动力"]].map(([x,y,n],i)=><button style={{left:`${x}%`,top:`${y}%`}} key={n} className={`atlas-pin pin-${i}`}><i/><span>{n}</span><b>{[86,92,77,83,71][i]}</b></button>)}<div className="atlas-legend"><span><i/>高度相关</span><span><i/>技术可迁移</span><span><i/>待核验</span></div></main><aside className="atlas-notes"><span>LAYER NOTE / {layer.toUpperCase()}</span><h2>{layer==="company"?"目标公司集群":layer==="role"?"岗位能力迁移":"研究方向邻近"}</h2><p>{layer==="company"?"北京与上海形成两个人才密度中心，具身智能本体与 VLA 团队存在明显交叉。":layer==="role"?"机器人平台负责人可向端到端算法负责人迁移，但需核验模型训练深度。":"多模态策略学习、世界模型和机器人数据闭环构成核心邻域。"}</p><div className="atlas-key"><span>覆盖公司</span><b>27</b></div><div className="atlas-key"><span>可迁移岗位</span><b>14</b></div><div className="atlas-key"><span>来源证据</span><b>193</b></div><button>打开研究结论</button></aside></section>;
}

function SearchNavigator() {
  const [point,setPoint]=useState(2);
  const points=["需求确认","机构信标","多源召回","证据核验","候选人交付"];
  return <section className="tech-main search-navigator"><header><div><Compass/><strong>DEEP SEARCH NAVIGATOR</strong><span>VOYAGE / 18H 32M</span></div><button><Anchor/>保存恢复锚点</button></header><main className="navigator-chart"><div className="nav-grid"/><svg viewBox="0 0 1000 620" preserveAspectRatio="none"><path className="contour c1" d="M30 470 C170 250 310 570 470 330 S760 180 960 280"/><path className="contour c2" d="M30 520 C220 330 320 630 520 400 S760 260 960 340"/><path className="route" d="M80 490 C210 390 250 430 360 320 S520 310 620 230 S800 250 900 120"/></svg>{points.map((item,i)=><button key={item} onClick={()=>setPoint(i)} className={`nav-beacon b${i} ${point===i?"active":""} ${i<point?"done":""}`}><i>{i<point?<Check/>:<Radio/>}</i><span>{item}</span><b>0{i+1}</b></button>)}<div className="sonar-pulse"/><div className="nav-coordinates">N 31°14' · E 121°28'</div></main><aside className="navigator-log"><span>ACTIVE BEACON / 0{point+1}</span><h1>{points[point]}</h1><p>{["确认组织别名、方向和时间范围。","解析机构实体与关联组织。","从多个数据源拉回候选论文。","核验身份、成果和公开资料。","生成分级结果等待确认。"][point]}</p><div className="nav-progress"><i><em style={{width:`${(point+1)*20}%`}}/></i><b>{(point+1)*20}%</b></div><dl><div><dt>已航行</dt><dd>18:32:41</dd></div><div><dt>发现对象</dt><dd>1,284</dd></div><div><dt>恢复锚点</dt><dd>07</dd></div></dl><div className="nav-discoveries"><span>最新发现</span>{["VLA 研究团队关联","新增 17 位作者","发现 4 条合作关系"].map(x=><button key={x}><i/><span>{x}</span><ChevronRight/></button>)}</div><button className="nav-open">查看完整航行记录</button></aside></section>;
}

function AgentWorkshop() {
  const [stage,setStage]=useState(2);
  const stages=["材料入槽","任务编排","质量门禁","产物交付"];
  return <section className="tech-main agent-workshop"><header><div><Code2/><strong>AGENT COMPILATION WORKSHOP</strong></div><span>JOB / COMPANY RESEARCH / 029</span><button><TimerReset/>重新编译</button></header><aside className="workshop-rack"><span>PROCESS RACK</span>{stages.map((item,i)=><button key={item} className={stage===i?"active":i<stage?"done":""} onClick={()=>setStage(i)}><i>{i<stage?<Check/>:i+1}</i><span>{item}</span><b>{i<stage?"PASS":i===stage?"RUN":"WAIT"}</b></button>)}<footer><PackageCheck/>输出规格 V3</footer></aside><main className="workshop-line"><div className="workshop-input"><span>INPUT MATERIAL</span><div><FileArchive/><b>理想汽车</b><small>仅提供公司名称</small></div></div><div className="workshop-conveyor"><span/><span/><span/><i className={`workpiece step-${stage}`}><Bot/><b>{stage+1}</b></i></div><div className="workshop-machine"><div className="machine-head"><Sparkles/><span>{stages[stage]}</span></div>{stage===0&&<div className="material-slots"><i>公司名</i><i>行业</i><i>公开网页</i></div>}{stage===1&&<div className="compile-code"><span>理解公司范围</span><span>规划信息来源</span><span>生成字段草稿</span></div>}{stage===2&&<div className="quality-gates"><i><Check/>结构</i><i><Check/>证据</i><i><Check/>标签</i><i className="running">… 格式</i></div>}{stage===3&&<div className="delivery-box"><PackageCheck/><b>公司草稿已就绪</b></div>}</div><div className="workshop-output"><span>OUTPUT BAY</span><div className={stage===3?"ready":""}><ClipboardCheck/><b>RESULT.JSON</b><small>{stage===3?"VALID":"WAITING"}</small></div></div></main><aside className="workshop-qc"><span>QUALITY CONTROL</span><div className="qc-score"><b>{stage===2?"03":"04"}</b><small>/ 04 GATES</small></div>{["字段白名单","证据可追溯","行业标签 ≤ 5","文本格式正确"].map((x,i)=><div key={x} className={i<stage+1?"pass":""}><i>{i<stage+1&&<Check/>}</i><span>{x}</span></div>)}<button><Stamp/>查看质量报告</button></aside></section>;
}

function AutomationRail() {
  const [station,setStation]=useState(2);
  const stations=["输入需求","AI 理解","人工确认","自动执行","结果审核","写入系统"];
  return <section className="tech-main automation-rail"><header><div><Navigation/><strong>AUTOMATION RAIL</strong><span>LINE 07 / POSITION ANALYSIS</span></div><button>查看全部线路</button></header><main><div className="rail-map">{stations.map((item,i)=><button key={item} onClick={()=>setStation(i)} className={station===i?"active":i<station?"passed":""}><i>{i<station?<Check/>:i+1}</i><span>{item}</span><small>{i===2||i===4?"人工站":"自动区间"}</small>{i<stations.length-1&&<em/>}</button>)}<div className={`rail-token stop-${station}`}><Bot/></div></div><article className="rail-station"><span>STATION / {String(station+1).padStart(2,"0")}</span><h1>{stations[station]}</h1><p>{["提交岗位原始描述和补充信息。","Agent 联网研究并形成岗位理解。","确认岗位范围、关键词和是否更新 JD。","并行运行寻访、匹配和证据核验。","检查候选人分层结果并决定写入。","通过门禁后写入正式业务资产。"][station]}</p><div className="station-actions"><button>查看上一步</button><button className="rail-primary">{station===2||station===4?"确认并继续":"查看运行过程"}<ArrowRight/></button></div></article></main><aside><span>LINE STATUS</span><div className="rail-status"><i/><div><b>等待人工确认</b><small>任务已在确认站停靠</small></div></div><dl><div><dt>已运行</dt><dd>08:42</dd></div><div><dt>自动区间</dt><dd>3 段</dd></div><div><dt>确认站</dt><dd>2 处</dd></div></dl><div className="rail-ticket"><small>TASK TICKET</small><strong>具身智能算法负责人</strong><span>POST-24-071</span></div><footer>偏航时进入旁路，不丢失结果。</footer></aside></section>;
}

function CollaborationMesh() {
  const [focus,setFocus]=useState("agent");
  const lanes=[{id:"human",name:"猎头",items:["确认需求","审核人选"]},{id:"agent",name:"Agent",items:["研究岗位","核验证据","生成建议"]},{id:"proof",name:"证据",items:["简历","公开网页","论文"]},{id:"asset",name:"业务资产",items:["岗位","候选人","Mapping"]}];
  return <section className="tech-main collaboration-mesh"><header><div><Network/><strong>MULTI-AGENT COLLABORATION MESH</strong></div><nav>{lanes.map(x=><button key={x.id} onClick={()=>setFocus(x.id)} className={focus===x.id?"active":""}>{x.name}</button>)}</nav><button><UsersRound/>协作成员 4</button></header><main className="mesh-board"><svg viewBox="0 0 1100 650" preserveAspectRatio="none"><path d="M190 115 C400 115 350 270 540 270 S700 425 920 425"/><path d="M190 280 C400 280 380 115 540 115 S730 280 920 280"/><path d="M190 445 C380 445 390 445 540 445 S720 115 920 115"/></svg>{lanes.map((lane,li)=><section key={lane.id} className={`mesh-lane lane-${lane.id} ${focus===lane.id?"active":""}`}><header><i>{li+1}</i><span>{lane.name}</span><b>{String(lane.items.length).padStart(2,"0")}</b></header><div>{lane.items.map((item,i)=><button key={item} onClick={()=>setFocus(lane.id)}><span>{lane.id==="agent"?<Bot/>:lane.id==="human"?<UserRoundCheck/>:lane.id==="proof"?<FileCheck2/>:<Database/>}</span><b>{item}</b><small>{i===0?"ACTIVE":"READY"}</small></button>)}</div></section>)}</main><aside><span>HANDOFF INSPECTOR</span><div className="mesh-focus"><i>{focus==="agent"?<Bot/>:focus==="human"?<UserRoundCheck/>:focus==="proof"?<FileCheck2/>:<Database/>}</i><div><b>{lanes.find(x=>x.id===focus).name}</b><small>当前聚焦泳道</small></div></div><h2>{focus==="agent"?"岗位研究 Agent 正在向证据泳道交付 4 条来源。":"选择对象查看交接详情。"}</h2><dl><div><dt>责任人</dt><dd>{focus==="human"?"于一凡":"Hunter Runtime"}</dd></div><div><dt>输入对象</dt><dd>7</dd></div><div><dt>交付对象</dt><dd>4</dd></div></dl><button><GitCompareArrows/>查看交接记录</button></aside></section>;
}

function PatternLibrary() {
  const [selected,setSelected]=useState([0]);
  const [query,setQuery]=useState("具身智能");
  const samples=useMemo(()=>[...candidates,{name:"苏晴",role:"机器人数据平台负责人",company:"原力智研",score:86,stage:"待确认"},{name:"许言",role:"多模态研究员",company:"智源研究院",score:82,stage:"人才储备"}],[]);
  return <section className="tech-main pattern-intelligence"><header><div><ScanSearch/><strong>PATTERN INTELLIGENCE LIBRARY</strong></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)}/><kbd>↵</kbd></label><button><ListFilter/>保存视图</button></header><aside><span>QUERY LATTICE</span>{["人物类型","技术模式","公司轨迹","项目证据","关系强度"].map((x,i)=><section key={x}><header><b>0{i+1}</b><span>{x}</span></header><button className={i<3?"active":""}>{["技术负责人","VLA / 机器人","创业公司 → 大厂","量产项目","二跳以内"][i]}<i>{i<3&&<Check/>}</i></button></section>)}<footer><Tags/>模式条件 <b>5</b></footer></aside><main><div className="pattern-toolbar"><span>匹配样本 126</span><div><button className="active">模式</button><button>列表</button></div><span>已选 {selected.length}</span></div><div className="sample-wall">{samples.map((item,i)=><button key={item.name} className={selected.includes(i)?"selected":""} onClick={()=>setSelected(x=>x.includes(i)?x.filter(v=>v!==i):[...x,i])}><div className="sample-visual"><span>{item.name.slice(0,1)}</span>{[0,1,2,3].map(n=><i key={n} style={{height:`${[item.score,72+i*3,84-i*2,66+i*4][n]}%`}}/>)}<em>{selected.includes(i)&&<Check/>}</em></div><strong>{item.name}</strong><small>{item.role}</small><footer><span>{item.company}</span><b>{item.score}</b></footer></button>)}</div></main><aside className="compare-tray"><span>COMPARE TRAY</span><strong>{String(selected.length).padStart(2,"0")}</strong><p>将候选人拖入托盘，系统对齐共同模式与差异证据。</p>{selected.map(i=><div key={i}><span>{samples[i].name.slice(0,1)}</span><div><b>{samples[i].name}</b><small>{samples[i].company}</small></div><button onClick={()=>setSelected(x=>x.filter(v=>v!==i))}>×</button></div>)}<button disabled={selected.length<2}><GitCompareArrows/>开始比较</button></aside></section>;
}

function FutureArchive() {
  const [item,setItem]=useState(0);
  const archive=[{name:"林昊",type:"关键人才",year:"2026",note:"具身智能算法负责人"},{name:"穹境机器人",type:"目标公司",year:"2026",note:"本体与 VLA 团队"},{name:"VLA 研究图谱",type:"研究成果",year:"2025",note:"论文与作者关系"}];
  return <section className="tech-main future-archive"><header><div><FileArchive/><strong>FUTURE TALENT ARCHIVE</strong></div><span>COLLECTION / EMBODIED AI</span><button><Search/>检索档案</button></header><aside className="archive-drawers"><span>ARCHIVE INDEX</span>{["关键人才","目标公司","岗位研究","学术成果","关系证据"].map((x,i)=><button key={x} className={i===0?"active":""}><b>A{i+1}</b><span>{x}</span><em>{[38,17,12,64,91][i]}</em></button>)}<footer><LibraryBig/>馆藏总量 <b>222</b></footer></aside><main><div className="archive-layers"><span className="archive-sheet sheet-back"><i>PROFILE / VERIFIED</i></span><span className="archive-sheet sheet-mid"><i>EVIDENCE / 19</i></span><article className="archive-sheet sheet-front"><header><span>{archive[item].type}</span><b>{archive[item].year}</b></header><div className="archive-portrait"><span>{archive[item].name.slice(0,1)}</span><i/><i/><i/></div><h1>{archive[item].name}</h1><p>{archive[item].note}</p><dl><div><dt>档案编号</dt><dd>FTA-026-{item+41}</dd></div><div><dt>证据完整</dt><dd>{[92,88,84][item]}%</dd></div><div><dt>最近更新</dt><dd>08 / 06</dd></div></dl></article></div><nav className="archive-timeline">{archive.map((x,i)=><button key={x.name} onClick={()=>setItem(i)} className={item===i?"active":""}><i/><span>{x.year}</span><b>{x.name}</b></button>)}</nav></main><aside className="archive-label"><span>CURATOR NOTE / 0{item+1}</span><h2>{archive[item].name}</h2><p>{["具备团队搭建、VLA 研发和真机量产的复合经验，是当前岗位的优先触达对象。","目标团队与具身智能方向高度相关，值得持续跟踪组织和招聘信号。","汇总论文、作者、机构和合作关系，为 Mapping 和岗位找人提供依据。"][item]}</p><div><small>关联岗位</small><b>{[3,5,2][item]}</b></div><div><small>关系路径</small><b>{[4,8,17][item]}</b></div><div><small>证据条目</small><b>{[19,27,64][item]}</b></div><button>打开完整档案 <ArrowRight/></button></aside></section>;
}

export const techLayoutsB = {
  "kinetic-ledger": TalentTape,
  "physical-telemetry": TelemetryStation,
  "institutional-trust": TrustProtocol,
  "ai-state-atlas": SemanticAtlas,
  "expedition-search": SearchNavigator,
  "compile-workshop": AgentWorkshop,
  "guided-service": AutomationRail,
  "teamwork-fabric": CollaborationMesh,
  "pattern-library": PatternLibrary,
  "digital-curatorial": FutureArchive,
};
